/* Árbol de equipos — Planta Tornquist (oct-2026).
   Fuente: listado de sistemas (Descripción + Sistema). Cada equipo: [SISTEMA, Descripción, ÁREA].
   - SISTEMA es el código único del lugar (el que va al Excel / EAM). El usuario elige por Descripción.
   - ÁREA se infirió comparando con el árbol anterior (revisable en el Excel "Arbol-equipos-revision.xlsx").
   - MAPEO_ARBOL_VIEJO: ubicación del árbol anterior ("AREA|SUBAREA|EQUIPO") -> SISTEMA, para QR viejos y tarjetas cargadas antes. */
const EQUIPOS = [
  ["AFILADORA", "Afiladora de cuchillas circulares Fileni", "ALISTAMIENTO"],
  ["GRUA.ELEVPRE", "Aparejo 10T Deposito Prensas", "ALISTAMIENTO"],
  ["GRUA.ELESADPT", "Aparejo 10T Descarga Prensas Salida Depósito Producto Terminado", "ALISTAMIENTO"],
  ["BLSORT", "Banda Lenta Sort 21. (cortadora)", "ALISTAMIENTO"],
  ["PC.BOAR", "Bomba Agua Refile Couch / Refile Vari Dur", "ALISTAMIENTO"],
  ["BOMPULPER REFILE", "Bomba Pulper Refile Vari Dur", "ALISTAMIENTO"],
  ["CORTCAÑOVARIDUR", "Cortadora Caños Vari Dur", "ALISTAMIENTO"],
  ["CORS.", "Cortadora Sort 21", "ALISTAMIENTO"],
  ["CORT.SINCHRO", "Cortadora Synchro", "ALISTAMIENTO"],
  ["CORT-ALI", "Cortina Aire Caliente Alistamiento", "ALISTAMIENTO"],
  ["LUG.ALIS.DEPOSITO", "Depósito", "ALISTAMIENTO"],
  ["DESB1.CORT.SORT", "Desbobinador N°1 Cortadora Sort", "ALISTAMIENTO"],
  ["DESB1.CORT.SINCHRO", "Desbobinador N°1 Cortadora Synchro", "ALISTAMIENTO"],
  ["DESB2.CORT.SORT", "Desbobinador N°2 Cortadora Sort", "ALISTAMIENTO"],
  ["DESB2.CORT.SINCHRO", "Desbobinador N°2 Cortadora Synchro", "ALISTAMIENTO"],
  ["COBO.IMSA", "Guillotina Bobinas IMSA", "ALISTAMIENTO"],
  ["GUILLPO", "Guillotina Polar", "ALISTAMIENTO"],
  ["MPSORT", "Mando Principal Sort 21", "ALISTAMIENTO"],
  ["MPSYNC", "Mando Principal Synchro", "ALISTAMIENTO"],
  ["MAN.VARIDUR1", "Mando Rollo Portador 1 Vari Dur motor dc", "ALISTAMIENTO"],
  ["MAN.VARIDUR2", "Mando Rollo Portador 2 Vari Dur motor dc", "ALISTAMIENTO"],
  ["MSCSORT21", "Mando Sincronismo de Corte Sort 21", "ALISTAMIENTO"],
  ["MSCSYNC", "Mando Sincronismo de Corte Synchro", "ALISTAMIENTO"],
  ["ALI.PMB", "Plato Movimiento Bobinas (Giratorio)", "ALISTAMIENTO"],
  ["PULPER REFILE", "Pulper Refile Vari Dur", "ALISTAMIENTO"],
  ["LUG.ALIS.REBOB", "Rebobinadora Vari Dur (general)", "ALISTAMIENTO"],
  ["REB-VEAXEXPO", "Ventilador Extractor Polvillo Axial Rebobinadora Vari Dur", "ALISTAMIENTO"],
  ["REB-VECEEXPO", "Ventilador Extractor Polvillo Centrífugo Rebobinadora Vari Dur", "ALISTAMIENTO"],
  ["REB-VEEXREF", "Ventilador Extractor Refile Vari Dur (Quick Draft)", "ALISTAMIENTO"],
  ["REB-VEROPULREF", "Ventilador Motor Rotor Pulper Refile Varidur", "ALISTAMIENTO"],
  ["REB-VEMOMAVA", "Ventilador Motores Mando Vari Dur", "ALISTAMIENTO"],
  ["ALI.VBAN", "Volcador Bancales Rogger", "ALISTAMIENTO"],
  ["ALI.VBOB", "Volcador Bobinas EHP", "ALISTAMIENTO"],
  ["LUG.ALIS.CORTADORA", "Zona Cortadora", "ALISTAMIENTO"],
  ["QUI-BBA1ANTINCRUSTANTE", "Bomba 1 (exterior) Anti incrustante Bombas de Vacio", "BOMBAS DE VACIO"],
  ["QUI-BBA2ANTINCRUSTANTE", "Bomba 2 (interior) Anti incrustante Bombas de Vacio", "BOMBAS DE VACIO"],
  ["VCIO.BOAS", "Bomba Agua Sello Bombas Vacio", "BOMBAS DE VACIO"],
  ["QUI-BODOAE", "Bomba Dosificadora Antiespumante bba. sello vacio", "BOMBAS DE VACIO"],
  ["BOMFIELTROS", "Bomba nivel piletin sello vacio fieltros", "BOMBAS DE VACIO"],
  ["VCIO.BOPIVACI", "Bomba Pierna Vacio CI", "BOMBAS DE VACIO"],
  ["VCIO.BOSUMI", "Bomba Sumidero Bombas Vacio", "BOMBAS DE VACIO"],
  ["VCIO.BO01", "Bomba Vacio BV01", "BOMBAS DE VACIO"],
  ["VCIO.BO02", "Bomba Vacio BV02", "BOMBAS DE VACIO"],
  ["VCIO.BO03", "Bomba Vacio BV03", "BOMBAS DE VACIO"],
  ["VCIO.BO04", "Bomba Vacio BV04", "BOMBAS DE VACIO"],
  ["VCIO.BO05", "Bomba Vacio BV05", "BOMBAS DE VACIO"],
  ["VCIO.BO06", "Bomba Vacio BV06", "BOMBAS DE VACIO"],
  ["VCIO.BO07", "Bomba Vacio BV07", "BOMBAS DE VACIO"],
  ["VCIO.BO08", "Bomba Vacio BV08", "BOMBAS DE VACIO"],
  ["VCIO.BO09", "Bomba Vacio BV09", "BOMBAS DE VACIO"],
  ["VCIO.BO10", "Bomba Vacio BV10", "BOMBAS DE VACIO"],
  ["VCIO.BO11", "Bomba Vacio BV11", "BOMBAS DE VACIO"],
  ["VCIO.BO12", "Bomba Vacio BV12", "BOMBAS DE VACIO"],
  ["VCIO.BO13", "Bomba Vacio BV13", "BOMBAS DE VACIO"],
  ["DUOVAC7A", "DUOVAC 7A", "BOMBAS DE VACIO"],
  ["DUOVAC7B", "DUOVAC 7B", "BOMBAS DE VACIO"],
  ["PILETIN SELLOS VACIOS FIELTROS", "Piletin sellos vacios fieltros", "BOMBAS DE VACIO"],
  ["SUMID BBAS VACIO", "Sumidero de Bombas de Vacio", "BOMBAS DE VACIO"],
  ["AGIT-CELL.TACACAAG", "Agitacion Tanque 1 Carbonato", "CELLIER"],
  ["AGIT-CELL.TACACAG2", "Agitacion Tanque 2 Carbonato", "CELLIER"],
  ["AGIT-CELL.TACACAG3", "Agitacion Tanque 3 Carbonato", "CELLIER"],
  ["AGIT-CELL.TQB1", "Agitador Tanque B1 Cellier", "CELLIER"],
  ["AGCOC1", "Agitador Tanque Cocinador C1 - Cellier", "CELLIER"],
  ["AGCOC2", "Agitador Tanque Cocinador C2 - Cellier", "CELLIER"],
  ["AGIT-CELL.TQE1", "Agitador Tanque E1 Cellier", "CELLIER"],
  ["AGIT-CELL.TQE2", "Agitador Tanque E2 Cellier", "CELLIER"],
  ["AGIT-CELL.TQE3", "Agitador Tanque E3 Cellier", "CELLIER"],
  ["AGIT-CELL.TQE4", "Agitador Tanque E4 Cellier", "CELLIER"],
  ["AGIT-CELL.TQE5", "Agitador Tanque E5 Cellier", "CELLIER"],
  ["AGIT-CELL.TQE6", "Agitador Tanque E6 Cellier", "CELLIER"],
  ["AGIT-CELL.TQE7", "Agitador Tanque E7 Cellier", "CELLIER"],
  ["AGIT-CELL.TQE8", "Agitador Tanque E8 Cellier", "CELLIER"],
  ["CELL.AGTQSODA", "Agitador Tanque Preparación Soda Cellier", "CELLIER"],
  ["APAREJC2CELLIER", "Aparejo Cocinador C2 Cellier", "CELLIER"],
  ["CELL.BOAGSED1", "Bomba 1 Agua Sello Dilutores", "CELLIER"],
  ["CELL.BOAGS2D1", "Bomba 2 Agua Sello Dilutores", "CELLIER"],
  ["BOMB1", "Bomba B1 Sistema Agua Fria Estucado", "CELLIER"],
  ["BOMB2", "Bomba B2 Sistema Agua Fria Estucado", "CELLIER"],
  ["CELL.BOCAPEF", "Bomba Captacion Efluentes Cellier", "CELLIER"],
  ["CELL.BODISPERSION", "Bomba Dispersion dilutores Cellier", "CELLIER"],
  ["CELL.BOL1", "Bomba Latex 1 Tqs 101 y 102", "CELLIER"],
  ["CELL.BOL2", "Bomba Latex 2 Envio a Dilutores", "CELLIER"],
  ["CELL.BOACED1", "Bomba Lubricacion Aceite Dilutor n°1", "CELLIER"],
  ["CELL.BONE67", "Bomba Neumatica Tanques E6 y E7", "CELLIER"],
  ["CELL.BOPE1", "Bomba PE1 Tanques E1/E2", "CELLIER"],
  ["CELL.BOPE2", "Bomba PE2 Tanques E4/E5", "CELLIER"],
  ["CELL.BOPE3", "Bomba PE3 Tanque E6", "CELLIER"],
  ["CELL.BOPE4", "Bomba PE4 Tanque E7", "CELLIER"],
  ["CELL.TACACABO", "Bomba Tanque 1 y 2 Carbonato Calcio Cellier", "CELLIER"],
  ["CELL.TACACABO3", "Bomba Tanque 3 Carbonato Calcio Cellier", "CELLIER"],
  ["CELL.DL01", "Dilutor N° 1", "CELLIER"],
  ["CELL.DL02", "Dilutor Nº 2", "CELLIER"],
  ["CELL.DL03", "Dilutor Nº 3", "CELLIER"],
  ["GRUA.MTACARCE", "Montacarga Cellier", "CELLIER"],
  ["MOTOVIBR-TOLCELL", "Motovibrador Tolva Carga Cellier", "CELLIER"],
  ["GRUA.ELEVCPCE", "Puente Grúa 2T Cellier", "CELLIER"],
  ["CELL.SOPCA", "Soplador Transporte Neumatico Caolin Cellier", "CELLIER"],
  ["CELL.VEXPD2Y3", "Ventilador Extractor Dilutores 2 y 3", "CELLIER"],
  ["CELL.VEXPD1", "Ventilador Extractor polvillo Dilutor N°1 Cellier", "CELLIER"],
  ["STCELL.EXT", "Ventilador Extractor Sala Tableros Cellier", "CELLIER"],
  ["VIB.BZATOL DIL", "Vibrador balanza Tolva Dilutor", "CELLIER"],
  ["CICO.CINTABM1", "Cinta BM 1", "CINTAS BAJO MAQ"],
  ["CICO.CINTABM2", "Cinta BM 2", "CINTAS BAJO MAQ"],
  ["CICO.CINTABM3", "Cinta BM 3", "CINTAS BAJO MAQ"],
  ["CICO.CINTABM4", "Cinta BM 4", "CINTAS BAJO MAQ"],
  ["CICO.CINTABM5", "Cinta BM 5", "CINTAS BAJO MAQ"],
  ["CICO.CINTABM6", "Cinta BM 6", "CINTAS BAJO MAQ"],
  ["CICO.CINTABM7", "Cinta BM 7", "CINTAS BAJO MAQ"],
  ["CICO.CINTABM8", "Cinta BM 8", "CINTAS BAJO MAQ"],
  ["CICO.CINTABM9", "Cinta BM 9", "CINTAS BAJO MAQ"],
  ["CINTABM - T", "Cinta BM TODAS", "CINTAS BAJO MAQ"],
  ["SCICO.SOPCBM9", "Soplador Cinta BM 9", "CINTAS BAJO MAQ"],
  ["ESTF.AGF1VARI", "Agitador Estación Final F1 Vari Bar", "ESTUCADO"],
  ["ESTF.AGF2LABI", "Agitador Estación Final F2 Labio Soplador", "ESTUCADO"],
  ["ESTF.AGF4UNIB", "Agitador Estación Final F3 Uni Bar", "ESTUCADO"],
  ["ESTF.AGF4COMB", "Agitador Estación Final F4 Combi Blade", "ESTUCADO"],
  ["AGIT-TQ 100 M3 CUP", "Agitador Tanque 100 m3 de cupertina", "ESTUCADO"],
  ["AGIT.TQ.RSEF", "Agitador Tanque Recupero Salsa Estaciones Finales", "ESTUCADO"],
  ["LABS.BORECCAJ", "Bomba Agua Polvillo Labio Soplador", "ESTUCADO"],
  ["TAQC.B114", "Bomba B114 Tanque Recirculación Cupertina", "ESTUCADO"],
  ["DRV058", "Bomba B114 Tq. Recir. Cup.(BOX 29.27.05)", "ESTUCADO"],
  ["VB.BOPF1", "Bomba Estación Final PF1 Vari Bar", "ESTUCADO"],
  ["LS.BOPF2", "Bomba Estación Final PF2 Labio Soplador", "ESTUCADO"],
  ["UB.BOPF3", "Bomba Estación Final PF3 Uni Bar", "ESTUCADO"],
  ["DRV149", "Bomba Estación Final Uni-Bar PF3 (BOX 22.01.1B)", "ESTUCADO"],
  ["DRV145", "Bomba Estación Final Vari-Bar PF1", "ESTUCADO"],
  ["MC.BOFAN", "Bomba Fan Mesa Cupertina", "ESTUCADO"],
  ["CB.BOPF4", "Bomba PF4 Estación Final Combi Blade", "ESTUCADO"],
  ["EST.BORS", "Bomba Recupero Salsa Estaciones Finales", "ESTUCADO"],
  ["BOMB-TQ 100 M3 CUP", "Bomba Tanque 100 m3 de cupertina", "ESTUCADO"],
  ["BOMB-TQ RECIR CI", "Bomba Tanque de recirculación de Capa intermedia", "ESTUCADO"],
  ["MANE.VEMOCC", "Booster Aire Combustion IR Estucado", "ESTUCADO"],
  ["CAVCUP7A", "Caja alto vacio Cupertina 7A", "ESTUCADO"],
  ["CAVCUP7B", "Caja alto vacio Cupertina 7B", "ESTUCADO"],
  ["CAL1.CHIDRA", "Central Hidraulica Rollo Kuster Calandra 1", "ESTUCADO"],
  ["MC.CECO", "Compresor Caja Formación Cupertina", "ESTUCADO"],
  ["DRV147", "Compresor Labio Soplador (BOX 90.03)", "ESTUCADO"],
  ["CONTRARODILLOCB", "Contrarrodillo Combi Blade", "ESTUCADO"],
  ["CONTRARODILLOLS", "Contrarrodillo Labio Soplador", "ESTUCADO"],
  ["CONTRARODILLOUB", "Contrarrodillo Uni Bar", "ESTUCADO"],
  ["CONTRARODILLOVB", "Contrarrodillo Vari Bar", "ESTUCADO"],
  ["ESTF.FI1RONCB", "Filtro 1 Ronninger Peter Combi Blade", "ESTUCADO"],
  ["ESTF.FI2RONCB", "Filtro 2 Ronninger Peter Combi Blade", "ESTUCADO"],
  ["LUG.EST.IRPRESEC", "Infrarrojos presecado (Solaronic)", "ESTUCADO"],
  ["VABA.INTNB01", "Intercambiador NA01 Vari Bar", "ESTUCADO"],
  ["INT1AGUAFRIA.LS", "Intercambiador N°1 Agua Fría Labio Soplador", "ESTUCADO"],
  ["INT2AGUAFRIA.LS", "Intercambiador N°2 Agua Fría Labio Soplador", "ESTUCADO"],
  ["MANCONTRARODILLOCB", "Mando Contrarrodillo Combi Blade (MECB)", "ESTUCADO"],
  ["MANCONTRARODILLOUB", "Mando Contrarrodillo UniBar (MEUB)", "ESTUCADO"],
  ["MANCONTRARODILLOVB", "Mando Contrarrodillo Vari Bar (MEVB)", "ESTUCADO"],
  ["VB.M15", "Mando M15 Sogas Vari Bar", "ESTUCADO"],
  ["CT1.M18MAN", "Mando M18 Cilindro Tiro 1", "ESTUCADO"],
  ["MC.M2MAN", "Mando M2 Rollo Mando Tela Cupertina", "ESTUCADO"],
  ["MAN.ME01", "Mando ME01 Rollo Papel, Pos. VB11, Vari Bar", "ESTUCADO"],
  ["MAN.ME02", "Mando ME02 Rollo Papel, Pos. VB19A, Vari Bar", "ESTUCADO"],
  ["MAN.ME03", "Mando ME03 Rollo Papel, Pos. VB21, Vari Bar", "ESTUCADO"],
  ["MAN.ME04", "Mando ME04 Rollo Papel, Pos. LS29, Labio Soplador", "ESTUCADO"],
  ["MAN.ME05", "Mando ME05 Rollo Papel, Pos. LS32, Labio Soplador", "ESTUCADO"],
  ["MAN.ME06", "Mando ME06 Rollo Papel, Pos. LS39, Labio Soplador", "ESTUCADO"],
  ["MAN.ME07", "Mando ME07 Rollo Tela, Pos T1-10, Cilindro Tiro 1", "ESTUCADO"],
  ["MAN.ME08", "Mando ME08 Rollo Papel, Pos. CB47, Combi Blade", "ESTUCADO"],
  ["MAN.ME09", "Mando ME09 Rollo Papel, Pos. CB56, Combi Blade", "ESTUCADO"],
  ["MAN.ME", "Mando ME10 (M-40-E10)", "ESTUCADO"],
  ["CAL1.MANS", "Mando Principal Calandra 1 (MEPC1)", "ESTUCADO"],
  ["MANRA-CB", "Mando Rollo aplicador Combi Balde", "ESTUCADO"],
  ["MANRA-LS", "Mando Rollo aplicador Labio Soplador", "ESTUCADO"],
  ["MANRA-UB", "Mando Rollo aplicador Uni bar (MERAU)", "ESTUCADO"],
  ["MANRA-VB", "Mando Rollo aplicador Vari bar", "ESTUCADO"],
  ["CAL1.MAN", "Mando Rollo Auxiliar Calandra 1 (MEAC1)", "ESTUCADO"],
  ["MANRPREA-LS", "Mando Rollo prealizador Labio Soplador", "ESTUCADO"],
  ["COMB.SO", "Mando Soga Combi Blade (MESG3)", "ESTUCADO"],
  ["LABS.SO", "Mando Soga Labio Soplador (MESLS)", "ESTUCADO"],
  ["VABA.SO", "Mando Soga Vari Bar (MESV)", "ESTUCADO"],
  ["MANDOS ESTUCADO", "Mandos ME01-ME09 Estucado ISU Sala Tableros 90-14", "ESTUCADO"],
  ["MANDOS MESA CUPERTINA", "Mandos Mesa Cupertina", "ESTUCADO"],
  ["RA-CB", "Rollo aplicador Combi Balde", "ESTUCADO"],
  ["RA-LS", "Rollo aplicador Labio Soplador", "ESTUCADO"],
  ["RA-UB", "Rollo aplicador Uni bar", "ESTUCADO"],
  ["SOP02.LS", "Soplador Labio Soplador Auxiliar", "ESTUCADO"],
  ["SOP01.LS", "Soplador Labio Soplador Titular", "ESTUCADO"],
  ["VCB", "Varilla Combi Blade", "ESTUCADO"],
  ["VUB", "Varilla Uni bar (MEVUB)", "ESTUCADO"],
  ["VVB", "Varilla Vari bar", "ESTUCADO"],
  ["MAXO.VECO", "Ventilador Aire Combustión Maxon 1 Combi Blade", "ESTUCADO"],
  ["MAXO.IIVECO", "Ventilador Aire Combustión Maxon 2 Uni Bar", "ESTUCADO"],
  ["SOL2.VECO", "Ventilador Aire Combustión Solaronic Combi Blade", "ESTUCADO"],
  ["SOL3.VECO", "Ventilador Aire Combustión Solaronic Labio Soplador", "ESTUCADO"],
  ["SOL1.VECO", "Ventilador Aire Combustión Solaronic Presecado", "ESTUCADO"],
  ["SOL4.VECO", "Ventilador Aire Combustión Solaronic UniBar", "ESTUCADO"],
  ["MAXO.VERE", "Ventilador Aire Recircirculacíon Maxon 1 Combi Blade", "ESTUCADO"],
  ["MAXO.IIVERE", "Ventilador Aire Recirculación Maxon 2 Uni Bar", "ESTUCADO"],
  ["SOL1.VERE", "Ventilador Aire Recirculación Solaronic Presecado", "ESTUCADO"],
  ["SOL4.VERE", "Ventilador Aire Recirculación Solaronic Uni Bar", "ESTUCADO"],
  ["SOL2.VERE", "Ventilador Aire Recirculación Solaronics Combi Blade", "ESTUCADO"],
  ["SOL.DUC", "Ventilador Ducto general solaronic", "ESTUCADO"],
  ["VECB.RO50", "Ventilador Enfriador Rollo Papel, Pos CB50, Combi Blade", "ESTUCADO"],
  ["VELS.RO32", "Ventilador Enfriador Rollo Papel, Pos LS32, Labio Soplador", "ESTUCADO"],
  ["VEUB.RO21", "Ventilador Enfriador Rollo Papel, Pos VB21, Uni Bar", "ESTUCADO"],
  ["LABS.VEEXPOL", "Ventilador Extractor Polvillo Labio Soplador", "ESTUCADO"],
  ["VENT-SMAX2", "Ventilador Extractor Sala Maxon 2", "ESTUCADO"],
  ["DRV134", "Ventilador General Ducto Solaronic (Box 22.00.09)", "ESTUCADO"],
  ["VMORA-LS", "Ventilador motor Rollo aplicador Labio Soplador", "ESTUCADO"],
  ["VEMORPREA-LS", "Ventilador Motor Rollo prealizador Labio Soplador", "ESTUCADO"],
  ["VENTIR2HLS", "Ventilador recirculación IR 2 hileras Labio Soplador", "ESTUCADO"],
  ["SOL3.VERE", "Ventilador recirculación IR 5 hileras Labio Soplador", "ESTUCADO"],
  ["ESTF.ZAF1VARI", "Zaranda Estación Final F1 Vari Bar", "ESTUCADO"],
  ["ESTF.ZAF2LABI", "Zaranda Estación Final F2 Labio Soplador", "ESTUCADO"],
  ["ESTF.ZAF4UNIB", "Zaranda Estación Final F3 Uni Bar", "ESTUCADO"],
  ["ESTF.ZARCOMB", "Zaranda Estación Final F4 Combi Blade", "ESTUCADO"],
  ["EFLU.AGPOLI1", "Agitador Agente Retención 1 Hidropolis", "HIDROPOLIS"],
  ["AGIT-PIL ACUM", "Agitador Pileta acumuladora", "HIDROPOLIS"],
  ["AGIT-TQ 100 M3 DORSO", "Agitador Tanque 100 m3 de dorso", "HIDROPOLIS"],
  ["AGIT-TQ 450 EFLUENTES", "Agitador Tanque 450 de efluentes", "HIDROPOLIS"],
  ["AGIT-TQ 450 PASTA", "Agitador Tanque 450 de pasta", "HIDROPOLIS"],
  ["AGIT-EFLU.POLI", "Agitador Tanque Agente Retención Hidropolis", "HIDROPOLIS"],
  ["APA.450PAST", "Aparejo Tanque 450m3 Pasta", "HIDROPOLIS"],
  ["BOMB-EFLU.POLI", "Bomba 1 Agente Retención Hidropolis", "HIDROPOLIS"],
  ["EFLU.BOTIT1", "Bomba 1 Efluente Hidropolis", "HIDROPOLIS"],
  ["DRV028", "Bomba 1 Pileta acumuladora (BOX 2A.04.06)", "HIDROPOLIS"],
  ["EFLU.BOSDF1", "Bomba 1 Sedifloat Hidropolis", "HIDROPOLIS"],
  ["BOMB-TQ 450 EFLUENTES", "Bomba 1 Tanque 450 de efluentes", "HIDROPOLIS"],
  ["EFLU.BOPOLI2", "Bomba 2 Agente Retención Hidropolis", "HIDROPOLIS"],
  ["EFLU.BOAUX2", "Bomba 2 Efluente Hidropolis", "HIDROPOLIS"],
  ["DRV035", "Bomba 2 Pileta acumuladora (BOX 2A.04.06)", "HIDROPOLIS"],
  ["EFLU.BOSDF2", "Bomba 2 Sedifloat Hidropolis", "HIDROPOLIS"],
  ["BOMB-TQ 450 EFLUENTES 2", "Bomba 2 Tanque 450 de efluentes", "HIDROPOLIS"],
  ["EFLU.BOAUX3", "Bomba 3 Efluentes Hidropolis", "HIDROPOLIS"],
  ["DRV014", "Bomba Hipoclorito Efluentes 2", "HIDROPOLIS"],
  ["BOMB-PIL ACUM", "Bomba N°1 Pileta acumuladora", "HIDROPOLIS"],
  ["BOMB2-PIL ACUM", "Bomba N°2 Pileta acumuladora", "HIDROPOLIS"],
  ["BOMB-HID.PR", "Bomba Pileta Pasta Recuperada Hidropolis", "HIDROPOLIS"],
  ["BOMB-TQ 450 PASTA", "Bomba Tanque 450 de pasta", "HIDROPOLIS"],
  ["BO.ADT", "Bomba TDA Hidropolis", "HIDROPOLIS"],
  ["CARROKROFTAHIDR", "Carro krofta hidropolis.Sedifloat 30", "HIDROPOLIS"],
  ["CUCHARAKROFTAHIDR", "Cuchara krofta hidropolis. Sedifloat 30", "HIDROPOLIS"],
  ["DENSI1", "Densidisc 1 Hidropolis", "HIDROPOLIS"],
  ["DENSI2", "Densidisc 2 Planta Pasta", "HIDROPOLIS"],
  ["DILD.DEZP302", "Dezurik Tanque 100 m3 Dorso", "HIDROPOLIS"],
  ["EFLU.RASTRI", "Rastrillo Canal Hidropolis", "HIDROPOLIS"],
  ["EFLUSEDI", "Sedifloat 30 Hidropolis (Krofta)", "HIDROPOLIS"],
  ["VENT-TABHIDRO", "Ventilador Presurización Sala de Tableros Hidropolis", "HIDROPOLIS"],
  ["VENT-HIDROPOLIS", "Ventilador Sala Hidropolis", "HIDROPOLIS"],
  ["EFLU.ZAR204N1", "Zaranda 204 Hidropolis", "HIDROPOLIS"],
  ["EFLU.ZAR205N2", "Zaranda 205 Hidropolis", "HIDROPOLIS"],
  ["EFLU.ZAR206N3", "Zaranda 206 Hidropolis", "HIDROPOLIS"],
  ["LUG.LAB.CALIDAD", "Laboratorio de Calidad", "LABORATORIO"],
  ["LUG.LAB.ENSAYOS", "Laboratorio · Equipos de ensayo", "LABORATORIO"],
  ["AGITPCOUCH", "Agitador Pozo Couch", "MESAS"],
  ["QUI.BOALM1SP", "Bomba 1 Almidón Spray", "MESAS"],
  ["QUI-BODOAE1", "Bomba 1 Dosificadora Antiespumante Mesas", "MESAS"],
  ["QUI.BOALM2SP", "Bomba 2 Almidón Spray", "MESAS"],
  ["QUI-BODOAE2", "Bomba 2 Dosificadora Antiespumante Mesas", "MESAS"],
  ["QUI-BODOAE3", "Bomba 3 Dosificadora Antiespumante Mesas", "MESAS"],
  ["BOAG4", "Bomba 4 dosificadora agente de retención Mesas", "MESAS"],
  ["BOAG5", "Bomba 5 dosificadora agente de retención Mesas", "MESAS"],
  ["QUI-BODOPOLR", "Bomba Agente Retención Aux Mesa Dorso / Cup N°3", "MESAS"],
  ["QUII.BODOPOL", "Bomba Agente Retención Mesa CI N°4", "MESAS"],
  ["QUII.BODOPOL5", "Bomba Agente Retención Mesa CI N°5", "MESAS"],
  ["QUIC.BODOPOL", "Bomba Agente Retención Mesa Cup N°1", "MESAS"],
  ["QUID.BODOPOL", "Bomba Agente Retención Mesa Dorso N°2", "MESAS"],
  ["DILC.BOTINDI", "Bomba B111 Dilucion Cup", "MESAS"],
  ["BOMCORTPC", "Bomba Corte Pozo Couch", "MESAS"],
  ["MD.BOFAN", "Bomba Fan Mesa Dorso", "MESAS"],
  ["BOMB-PIL102C", "Bomba Pileta 102", "MESAS"],
  ["DRV137", "Bomba Pileta 102 (Box)", "MESAS"],
  ["BOMB-PIL270I", "Bomba Pileta 270", "MESAS"],
  ["BOMREFPC", "Bomba Refile Pozo Couch", "MESAS"],
  ["TAQC.BOSPITSE", "Bomba Seal Pit Cupertina", "MESAS"],
  ["BOMB-QUI.TQ2AL", "Bomba Tanque 2 (Estación Final) Almidón Spray", "MESAS"],
  ["CAF-CI", "Caja Formación CI", "MESAS"],
  ["CAF-CUP", "Caja Formación Cup", "MESAS"],
  ["CAF-DOR", "Caja Formación Dorso", "MESAS"],
  ["MI.CECO", "Compresor Caja Formación CI", "MESAS"],
  ["MD.CECO", "Compresor Caja Formación Dorso", "MESAS"],
  ["MD.V22", "Depurador V22 Dorso", "MESAS"],
  ["MDOAGITPCOUCH", "Mando Agitador Pozo Couch", "MESAS"],
  ["MC.M1MAN", "Mando M1 Rollo Mando Tela Cup", "MESAS"],
  ["MC.M4MAN", "Mando M4 Rollo Mando Tela Dorso", "MESAS"],
  ["MC.M5MAN", "Mando M5 Rollo Transferencia Dorso", "MESAS"],
  ["MC.M6MAN", "Mando M6 Rollo Mando Tela CI", "MESAS"],
  ["MC.M7MAN", "Mando M7 Rollo Transferencia CI", "MESAS"],
  ["MC.M8MAN", "Mando M8 Rollo Aux CI", "MESAS"],
  ["MC.M9MAN", "Mando M9 Rollo Mando Tela Top Former", "MESAS"],
  ["MANDO TQ ALMI MESAS", "Mando Tanque Almidon Mesas (bomb desc tq almac almi pulp)", "MESAS"],
  ["MANDOS MESA CAPA INTERMEDIA", "Mandos Mesa Capa Intermedia", "MESAS"],
  ["MANDOS MESA DORSO", "Mandos Mesa Dorso", "MESAS"],
  ["PTAAGRET", "Planta Preparación Agente de Retención Mesas", "MESAS"],
  ["GRUA.ELEVC1M", "Puente Grúa 10T Demag Mesas", "MESAS"],
  ["GRUA.GRUABEL", "Puente Grúa 2T ABUS Mesas", "MESAS"],
  ["TECI.REROCUP", "Regadera rotativa caja de formación Cup", "MESAS"],
  ["MD.RO300", "Rollo Cabeza, Pos 300 Mesa Dorso", "MESAS"],
  ["RO.DIST1CUP", "Rollo Distrib. 1, Pos. 101 Mesa Cup", "MESAS"],
  ["RO.DIST1CI", "Rollo Distrib. 1, Pos. 201 Mesa CI", "MESAS"],
  ["RO.DIST1DOR", "Rollo Distrib. 1, Pos. 301 Mesa Dorso", "MESAS"],
  ["RO.DIST2CUP", "Rollo Distrib. 2, Pos. 102 Mesa Cup", "MESAS"],
  ["RO.DIST2CI", "Rollo Distrib. 2, Pos. 202 Mesa CI", "MESAS"],
  ["RO.DIST2DOR", "Rollo Distrib. 2, Pos. 302 Mesa Dorso", "MESAS"],
  ["TRAQUEOCI", "Rollo Traqueo CI", "MESAS"],
  ["TRAQUEOCUP", "RolloTraqueo Cupertina", "MESAS"],
  ["TRAQUEODOR", "RolloTraqueo Dorso", "MESAS"],
  ["TF.VENVACMFCS", "Ventilador MFVB1 Top Former", "MESAS"],
  ["MI.VEVF", "Ventilador Vacuum Foil Mesa CI", "MESAS"],
  ["MC.VEVF", "Ventilador Vacuum Foil Mesa Cup", "MESAS"],
  ["MD.VEVF", "Ventilador Vacuum Foil Mesa Dorso", "MESAS"],
  ["CICO.BOCOPBM", "Bomba Agua de Corte PBM", "PILETA AGUA CORTE"],
  ["CICO.BOAG", "Bomba Agua de Corte Pozo Couch", "PILETA AGUA CORTE"],
  ["BOM-PUL", "Bomba Agua Dilucion Pulpo", "PILETA AGUA CORTE"],
  ["PILAC.BOM", "Bomba Mezcla Pileta Agua de Corte", "PILETA AGUA CORTE"],
  ["BOMB-PIL AGUA CORTE", "Bomba Pileta agua de corte", "PILETA AGUA CORTE"],
  ["AGIT-PIL102C", "Agitador Pileta 102", "PILETAS LC"],
  ["AGIT-PIL103C", "Agitador Pileta 103", "PILETAS LC"],
  ["AGIT-PIL220I", "Agitador Pileta 220", "PILETAS LC"],
  ["AGIT-PIL.242", "Agitador Pileta 242", "PILETAS LC"],
  ["AGIT-PIL270I", "Agitador Pileta 270", "PILETAS LC"],
  ["AGIT-PIL.301", "Agitador Pileta 301", "PILETAS LC"],
  ["AGIT-PIL303D", "Agitador Pileta 303", "PILETAS LC"],
  ["AGIT-PIL304D", "Agitador Pileta 304", "PILETAS LC"],
  ["DRV115", "Bomba Pileta 102 (BOX 08.11.05)", "PILETAS LC"],
  ["BOMB-PIL103C", "Bomba Pileta 103", "PILETAS LC"],
  ["BOMB-PIL220I", "Bomba Pileta 220", "PILETAS LC"],
  ["BOMB-PIL.242", "Bomba Pileta 242", "PILETAS LC"],
  ["DRV096", "Bomba pileta 242 (BOX 04.08)", "PILETAS LC"],
  ["BOMB-PIL.301", "Bomba Pileta 301", "PILETAS LC"],
  ["BOMB-PIL303D", "Bomba Pileta 303", "PILETAS LC"],
  ["BOMB-PIL304D", "Bomba Pileta 304", "PILETAS LC"],
  ["DILC.DEZP102", "BTG Pileta 102", "PILETAS LC"],
  ["DILI.DEZP201B", "Dezurik Pileta 220", "PILETAS LC"],
  ["DILA.DEZ242", "Dezurik Pileta 242", "PILETAS LC"],
  ["DILI.DEZP270", "Dezurik Pileta 270", "PILETAS LC"],
  ["DILD.DEZP303", "Dezurik Pileta 303", "PILETAS LC"],
  ["AGIT-PIL403", "Agitacion Pileta 403", "PILETAS LM"],
  ["AGIT-PIL101C", "Agitador Pileta 101", "PILETAS LM"],
  ["AGIT-PIL.401", "Agitador Pileta 205", "PILETAS LM"],
  ["AGIT-PIL210I", "Agitador Pileta 210", "PILETAS LM"],
  ["AGIT-PIL401", "Agitador Pileta 401", "PILETAS LM"],
  ["BOMB-PIL-A", "Bomba 1 Pileta A", "PILETAS LM"],
  ["BOR-BORIO1", "Bomba 1 Río", "PILETAS LM"],
  ["PLA.BOACHILAM", "Bomba 2 Laminado (Corral)", "PILETAS LM"],
  ["BOMB-PIL-A2", "Bomba 2 Pileta A", "PILETAS LM"],
  ["BOR-BORIO2", "Bomba 2 Río", "PILETAS LM"],
  ["TECC.BOAGCIR", "Bomba Agua Circulante Tec Blanes", "PILETAS LM"],
  ["AGRE.BOELU", "Bomba Agua Elutriación", "PILETAS LM"],
  ["BOM.REDINCEN", "Bomba agua Red Incendios", "PILETAS LM"],
  ["CELL.BOAGTANQ", "Bomba Auxiliar Cellier", "PILETAS LM"],
  ["MC.BODP", "Bomba B109 Depuración 1º Cup (DR 2000)", "PILETAS LM"],
  ["MC.BOV12", "Bomba B112 Depurador V12 Cup", "PILETAS LM"],
  ["BOMB4", "Bomba B4 Sistema Agua Fria Estucado", "PILETAS LM"],
  ["BOMB5", "Bomba B5 Sistema Agua Fria Estucado", "PILETAS LM"],
  ["BOMB6", "Bomba B6 Sistema Agua Fria Estucado", "PILETAS LM"],
  ["BO-RIO1", "Bomba de rio 1", "PILETAS LM"],
  ["BO-RIO2", "Bomba de rio 2", "PILETAS LM"],
  ["MI.BODP", "Bomba Depuración 1º CI (DC1)", "PILETAS LM"],
  ["MD.BODP", "Bomba Depuración 1º Dorso", "PILETAS LM"],
  ["MI.BODS", "Bomba Depuración 2º CI (DC2)", "PILETAS LM"],
  ["MD.BODS", "Bomba Depuración 2º Dorso", "PILETAS LM"],
  ["MI.BODT", "Bomba Depuración 3º CI (DC3)", "PILETAS LM"],
  ["MD.BODT", "Bomba Depuración 3º Dorso", "PILETAS LM"],
  ["MI.BAV12", "Bomba Depurador DP2 CI", "PILETAS LM"],
  ["MD.BAV12", "Bomba Depurador V12 Dorso", "PILETAS LM"],
  ["MI.BOFAN", "Bomba Fan Mesa CI", "PILETAS LM"],
  ["ALIM.BORONN", "Bomba Filtros Agua Ronningen Peter", "PILETAS LM"],
  ["ALIM.BOGR1", "Bomba Grundfos 1 20 Bar", "PILETAS LM"],
  ["ALIM.BOKO1", "Bomba Kobe 1 20 Bar (Gundfos)", "PILETAS LM"],
  ["ALIM.BOKO2", "Bomba Kobe 2 20 Bar", "PILETAS LM"],
  ["ALIM.BOKO4", "Bomba Kobe 4 20 Bar", "PILETAS LM"],
  ["BOMB-PIL101C", "Bomba Pileta 101", "PILETAS LM"],
  ["BOMB-PIL205", "Bomba Pileta 205", "PILETAS LM"],
  ["BOMB-PIL210I", "Bomba Pileta 210", "PILETAS LM"],
  ["DRV003", "Bomba pileta 210 (BOX 08.12.04)", "PILETAS LM"],
  ["BOMB-PIL401", "Bomba Pileta 401", "PILETAS LM"],
  ["BOMB-PIL403", "Bomba Pileta 403", "PILETAS LM"],
  ["BOMB-PIL AGUA A CLAR EFLU", "Bomba Pileta agua a clarificar de efluentes", "PILETAS LM"],
  ["BOMB-TEC.TAC", "Bomba Pileta Agua Circulante (TAC) Cupertina", "PILETAS LM"],
  ["BOMB-PAC.CUP", "Bomba Pileta Agua Circulante Tec Blanes", "PILETAS LM"],
  ["BOMB-PIL-B", "Bomba Pileta B", "PILETAS LM"],
  ["BOMB-EFLU.SUPIPU", "Bomba Pileta Pulmón Triangular", "PILETAS LM"],
  ["ALIM.BOREG", "Bomba Regadera 3.5 Bar", "PILETAS LM"],
  ["BOMB-QUI-TQ1AE", "Bomba Tanque 1 Antiespumante", "PILETAS LM"],
  ["BOMB-CLAV.AC1", "Bomba Tanque 1 Lavado Acido Telas y Fieltros", "PILETAS LM"],
  ["BOMB-QUI-TQ2AE", "Bomba Tanque 2 Antiespumante", "PILETAS LM"],
  ["BOMB-CLAV.AC2", "Bomba Tanque 2 Lavado Acido Telas y Fieltros", "PILETAS LM"],
  ["BOMB-TQ231CI.BO", "Bomba Tanque 231", "PILETAS LM"],
  ["DRV098", "Bomba tanque 231 (BOX 0A.03)", "PILETAS LM"],
  ["BOMB-TQ 241", "Bomba Tanque 241", "PILETAS LM"],
  ["BOMB-TQ 243", "Bomba Tanque 243", "PILETAS LM"],
  ["DRV095", "Bomba Tanque 243 (BOX 04.08)", "PILETAS LM"],
  ["BOMB-T302D", "Bomba Tanque 302 Dorso", "PILETAS LM"],
  ["BO.TQ305", "Bomba Tanque 305", "PILETAS LM"],
  ["DRV057", "Bomba Tanque 305 (BOX 29.27.05)", "PILETAS LM"],
  ["BOMB-TQ 50 M3 TETRA", "Bomba Tanque 50 m3 Tetra y CTMP", "PILETAS LM"],
  ["BC4TQVACIO", "Bomba Tanque de Vacio Auxiliar BC4", "PILETAS LM"],
  ["BOMB-TRAG.TQDSCA", "Bomba Tanque Descarbonatadora", "PILETAS LM"],
  ["BOMB-TQ REB AGUA DEP", "Bomba Tanque rebalse agua depuración CI", "PILETAS LM"],
  ["PULD.TQREDOBO", "Bomba Tanque Recupero Dorso", "PILETAS LM"],
  ["DC240", "Depurador centrifugo DC240", "PILETAS LM"],
  ["MI.V12", "Depurador V12 CI (DP2)", "PILETAS LM"],
  ["MC.V12", "Depurador V12 Cupertina", "PILETAS LM"],
  ["MI.V22", "Depurador V22 CI (DP1)", "PILETAS LM"],
  ["MC.V22", "Depurador V22 Cupertina", "PILETAS LM"],
  ["DILC.DEZP101", "Dezurik Pileta 101", "PILETAS LM"],
  ["DILI.DEZP210", "Dezurik Pileta 210", "PILETAS LM"],
  ["DILC.DEZTINAB", "Dezurik Tina Pasta Tec Blanes", "PILETAS LM"],
  ["AGRE.BOACHCDS", "Bomba Achique Sótano Condensado", "PLANTA CONDENSADO"],
  ["BBAINTERPTACOND", "Bomba Agua Intercambiador Planta Condensado", "PLANTA CONDENSADO"],
  ["BV1PTACOND", "Bomba de Vacio BV1 Planta Condensado", "PLANTA CONDENSADO"],
  ["BV2PTACOND", "Bomba de Vacio BV2 Planta Condensado", "PLANTA CONDENSADO"],
  ["BC3TQVACIO", "Bomba Tanque de Vacio Titular BC3", "PLANTA CONDENSADO"],
  ["BOMBC6TQPULMON", "Bomba Tanque pulmon Auxiliar BC6", "PLANTA CONDENSADO"],
  ["BOMBC5TQPULMON", "Bomba Tanque Pulmon Titular BC5", "PLANTA CONDENSADO"],
  ["INTERPTACOND", "Intercambiador Planta Condensado", "PLANTA CONDENSADO"],
  ["GRUA.ELEVPLPA", "Aparejo 1T Planta Pasta", "PLANTA DE PASTA"],
  ["GRUA.CARTMAULE", "Aparejo sobre portón Maule", "PLANTA DE PASTA"],
  ["TAQI.BOACITI", "Bomba Agua Dilucion 5 CI (A Tina Maule)", "PLANTA DE PASTA"],
  ["TECI.RESEBO", "Bomba Regaderas Separplast", "PLANTA DE PASTA"],
  ["TECI.CINTA01", "Cinta 1 Saca Pasta Prensa Maule", "PLANTA DE PASTA"],
  ["TECI.CINTA02", "Cinta 2 Saca Pasta Prensa Maule", "PLANTA DE PASTA"],
  ["CORT-MAULE", "Cortina Metalica Maule", "PLANTA DE PASTA"],
  ["TECI.DI", "Dispersor 250 Tec Maule", "PLANTA DE PASTA"],
  ["FAN.SEPARATOR", "Fan Separator 241 (Maule)", "PLANTA DE PASTA"],
  ["FAN.SEPARATORCI", "Fan Separator CI (Blanes)", "PLANTA DE PASTA"],
  ["FISEP 301", "FIBER SEPARATOR F 301 GLM DX 720 (REEMPLAZO AL FIBERIZER 301)", "PLANTA DE PASTA"],
  ["FIBC.F1", "Fiberizer F101", "PLANTA DE PASTA"],
  ["FIBI.241", "Fiberizer F241", "PLANTA DE PASTA"],
  ["FIBD.302", "Fiberizer F302", "PLANTA DE PASTA"],
  ["FIBERNET241", "Fibernet 241", "PLANTA DE PASTA"],
  ["FRACC220", "Fraccionador 220", "PLANTA DE PASTA"],
  ["LUG.PP.GENERAL", "Planta de Pasta (general)", "PLANTA DE PASTA"],
  ["GRUA.ELEVSMAU", "Pluma Giratoria 3T Maule", "PLANTA DE PASTA"],
  ["TECI.PD250", "Prensa Deshidratadora 250 Tec Maule", "PLANTA DE PASTA"],
  ["GRUA.ELEVCPMA", "Puente Grúa 5T Maule", "PLANTA DE PASTA"],
  ["REF.R101", "Refinador R101", "PLANTA DE PASTA"],
  ["REF.R102", "Refinador R102", "PLANTA DE PASTA"],
  ["REF.R201", "Refinador R271 (DSR1)", "PLANTA DE PASTA"],
  ["REF.R272", "Refinador R272 (DSR2)", "PLANTA DE PASTA"],
  ["REF.R301", "Refinador R301", "PLANTA DE PASTA"],
  ["REF.R302", "Refinador R302", "PLANTA DE PASTA"],
  ["SACASAN 1", "Sac-A-San 1 - DC3 (Planta de Pasta)", "PLANTA DE PASTA"],
  ["SEPARPLAST", "Separplast 231", "PLANTA DE PASTA"],
  ["SEPARTPLAST", "Separplast 232", "PLANTA DE PASTA"],
  ["TECI.RET251", "Tornillo 251 Tec Maule", "PLANTA DE PASTA"],
  ["TECI.RET252", "Tornillo 252 Tec Maule", "PLANTA DE PASTA"],
  ["TECI.RET253", "Tornillo 253 Tec Maule", "PLANTA DE PASTA"],
  ["VENT1PP", "Ventilador 1 Planta de Pasta", "PLANTA DE PASTA"],
  ["VENT10PP", "Ventilador 10 Planta de Pasta", "PLANTA DE PASTA"],
  ["VENT2PP", "Ventilador 2 Planta de Pasta", "PLANTA DE PASTA"],
  ["VENT3PP", "Ventilador 3 Planta de Pasta", "PLANTA DE PASTA"],
  ["VENT4PP", "Ventilador 4 Planta de Pasta", "PLANTA DE PASTA"],
  ["VENT5PP", "Ventilador 5 Planta de Pasta", "PLANTA DE PASTA"],
  ["VENT6PP", "Ventilador 6 Planta de Pasta", "PLANTA DE PASTA"],
  ["VENT7PP", "Ventilador 7 Planta de Pasta", "PLANTA DE PASTA"],
  ["VENT8PP", "Ventilador 8 Planta de Pasta", "PLANTA DE PASTA"],
  ["VENT9PP", "Ventilador 9 Planta de Pasta", "PLANTA DE PASTA"],
  ["VENT-TABPP", "Ventilador Presurización Sala de tableros Planta de pasta", "PLANTA DE PASTA"],
  ["VIFAN.SEPARATOR", "Vibrador Fan Separator 241 (Maule)", "PLANTA DE PASTA"],
  ["ZARC.102", "Zaranda 102", "PLANTA DE PASTA"],
  ["ZARI.ZARSEPAR", "Zaranda 230 (Separplast)", "PLANTA DE PASTA"],
  ["ACPOPE.MAN", "Acelerador de Barras Pope", "POPE"],
  ["DRV068", "Acelerador de Barras.(BOX 90.14.03)", "POPE"],
  ["BOMB7", "Bomba B7 Agua Fria 6°Bat, Pope y Varidur", "POPE"],
  ["BBADUOVAC01", "Bomba DUOVAC N°1 (Lado Pope)", "POPE"],
  ["ESCANER BX", "Escaner - Beltronix", "POPE"],
  ["ESCANER VM", "Escaner - Valmet", "POPE"],
  ["POPE.MAN", "Mando Pope (MEPPE)", "POPE"],
  ["LUG.POPE", "Pope (general)", "POPE"],
  ["GRUA.ELEVCPPO", "Puente Grúa 10T Pope", "POPE"],
  ["LUG.PREN.PRENSA1", "1ª Prensa (general)", "PRENSAS"],
  ["BO1TEMSEC", "Bomba 1 central hidraúlica Tem Sec", "PRENSAS"],
  ["PR.LAMBO", "Bomba 1 Laminado (Prensa)", "PRENSAS"],
  ["BO2TEMSEC", "Bomba 2 central hidraúlica Tem Sec", "PRENSAS"],
  ["BO1ACEITEMSEC", "Bomba aceite 1 reductor Tem Sec", "PRENSAS"],
  ["BO2ACEITEMSEC", "Bomba aceite 2 reductor Tem Sec", "PRENSAS"],
  ["PULI.CORRAL", "Bomba Achique Corral (Laminado)", "PRENSAS"],
  ["PULI.LAMINADO", "Bomba Achique Prensa (Laminado)", "PRENSAS"],
  ["BBA TQ AGUA LIMP TEM SEC", "Bomba TQ colector de aguas limpias de Tem-Sec", "PRENSAS"],
  ["BOVACTQREC.TEMSEC", "Bomba vaciado Tq recolector agua Tem Sec", "PRENSAS"],
  ["CENHIPORT", "Central Hidraúlica Portón Larga Acceso", "PRENSAS"],
  ["CENHIPORT 1", "Central Hidraúlica Puerta Acceso Personal", "PRENSAS"],
  ["1P.M10MAN", "Mando M10 1° Prensa", "PRENSAS"],
  ["2P.M11MAN", "Mando M11 2° Prensa", "PRENSAS"],
  ["TEMS.M12CIBA", "Mando M12A Cilindro Base Tem Sec", "PRENSAS"],
  ["TSNIP1.M12B", "Mando M12B Tem Sec 1º Nip", "PRENSAS"],
  ["TSNIP2.M12C", "Mando M12C Tem Sec 2º Nip", "PRENSAS"],
  ["TEMS.M12ROSAL", "Mando M12D Rollo Salida Tem Sec", "PRENSAS"],
  ["PRENSA-TETRA Y CTMP", "Prensa Enfardadora Horizontal Tetra y CTMP", "PRENSAS"],
  ["ROSCA-TETRA Y CTMP", "Rosca transportadora Tetra y CTMP", "PRENSAS"],
  ["LUG.PREN.TEMSEC", "Tem Sec (general)", "PRENSAS"],
  ["AGRE.BOACHIPOP", "Bomba Achique Sótano Pulper Bajo Máquina", "PULPER BAJO MAQUINA"],
  ["BOMBEO PBM", "Bomba Pulper Bajo Maquina", "PULPER BAJO MAQUINA"],
  ["ROTOR 1 PBM", "Rotor 1 Pulper Bajo Maquina", "PULPER BAJO MAQUINA"],
  ["ROTOR 2 PBM", "Rotor 2 Pulper Bajo Maquina", "PULPER BAJO MAQUINA"],
  ["QUI.AGALM1SP", "Agitador Tanque 1 Almidón Spray", "PULPERS"],
  ["QUI.AGALM2SP", "Agitador Tanque 2 Almidón Spray", "PULPERS"],
  ["AGIT-AP.TQA", "Agitador Tanque Almacenamiento Almidon Pulpers", "PULPERS"],
  ["AGIT-AP.TQC", "Agitador Tanque Cocinador Almidon Pulpers", "PULPERS"],
  ["QUI.AGTOALSP", "Agitador Tolva Almidón Spray", "PULPERS"],
  ["APAREJO-ASPRAY", "Aparejo 1.5T Almidón Spray", "PULPERS"],
  ["GRUA.ELAPST20", "Aparejo 1T Pulper E20", "PULPERS"],
  ["GRUA.ELEVPULC", "Aparejo 1T Pulper E21", "PULPERS"],
  ["GRUA.ELEVPULD", "Aparejo 1T Pulper E22", "PULPERS"],
  ["GRUA.ELEVSOTPUL", "Aparejo 1T Sótano Pulpers", "PULPERS"],
  ["PULI.D30BOACH", "Bomba Achique Canal D30", "PULPERS"],
  ["PULS.ACHBO", "Bomba Achique Sótano Pulpers", "PULPERS"],
  ["TAQI.BOACI201", "Bomba Agua Dilucion 2 (A P210, Tq 200 D30)", "PULPERS"],
  ["BBA LAVADO PWC02", "Bomba agua lavado Pulper Washer", "PULPERS"],
  ["BOMB-AP.TQA", "Bomba Descaga Tanque Almacenamiento Almidon Pulpers", "PULPERS"],
  ["BOMPULPER D30", "Bomba Descarga Pulper D30", "PULPERS"],
  ["BOMBPULPER E20", "Bomba Descarga Pulper E20", "PULPERS"],
  ["BOMPULPER E21", "Bomba Descarga Pulper E21", "PULPERS"],
  ["BOMPULPER E22", "Bomba Descarga Pulper E22", "PULPERS"],
  ["BOMB-AP.TQC", "Bomba Descarga Tanque Cocinador Almidon Pulpers", "PULPERS"],
  ["BBADUOVAC02", "Bomba DUOVAC N°2 (Lado Pulpers)", "PULPERS"],
  ["BOMB-TQ200 D30", "Bomba Tanque 200 pulper D30", "PULPERS"],
  ["SIN-CODIGO-BOMBATRIVAC7BL", "Bomba TRIVAC7B (Lado Pulpers) (Ex-DUOVAC N°2)", "PULPERS"],
  ["CINTA D30", "Cinta Pulper D30 (CINTA D30)", "PULPERS"],
  ["DRV005", "Cinta Pulper D30 (DRV005)", "PULPERS"],
  ["CINTA E20", "Cinta Pulper E20", "PULPERS"],
  ["CINTA E21", "Cinta Pulper E21", "PULPERS"],
  ["CINTA E22", "Cinta Pulper E22", "PULPERS"],
  ["CORT-D30", "Cortina Metalica D-30", "PULPERS"],
  ["DESTERR-ASPRAY", "Desterronador Almidón Spray", "PULPERS"],
  ["DILI.DEZPULI", "Dezurik Pulper D30", "PULPERS"],
  ["DILC.DEZPUL20", "Dezurik Pulper E20", "PULPERS"],
  ["DILI.DEZPULE21", "Dezurik Pulper E21", "PULPERS"],
  ["DILD.DEZPULD", "Dezurik Pulper E22", "PULPERS"],
  ["DILI.DEZTQ200D30", "Dezurik Tanque 200 D30", "PULPERS"],
  ["PUL.FAAL", "Enfardadora Alambre Pulpers", "PULPERS"],
  ["FIBERIZER D30", "Fiberizer Pulper D30", "PULPERS"],
  ["FIBERIZER E20", "Fiberizer Pulper E20", "PULPERS"],
  ["MDODTROMMEL D30", "Mando Derecho Trommel Pulper D30", "PULPERS"],
  ["MDODTROMMEL E20", "Mando Derecho Trommel Pulper E20", "PULPERS"],
  ["MDODTROMMEL E22", "Mando Derecho Trommel Pulper E22", "PULPERS"],
  ["MDOTROMMEL D30", "Mando Izquierdo Trommel Pulper D30", "PULPERS"],
  ["MDOITROMMEL E20", "Mando Izquierdo Trommel Pulper E20", "PULPERS"],
  ["MEZTDOSIFIC-ASPRAY", "Mezclador Tolva Dosificadora Almidón Spray", "PULPERS"],
  ["MIX-PULPER E22", "Misturex Pulper E22 Tetra y CTMP", "PULPERS"],
  ["MOTOVIBR-ASPRAY", "Motovibrador Tolva Big Bag Almidón Spray", "PULPERS"],
  ["GRUA.APD30", "Pluma Giratoria 3TN Pulper D30", "PULPERS"],
  ["GRUA.GRUAEL", "Puente Grúa 3TN Pulper D30", "PULPERS"],
  ["PULPER D30", "Pulper D30", "PULPERS"],
  ["PULPER E20", "Pulper E20", "PULPERS"],
  ["PULPER E21", "Pulper E21", "PULPERS"],
  ["PULPER E22", "Pulper E22", "PULPERS"],
  ["PULPER WASHER D30", "Pulper Washer Pulper D30", "PULPERS"],
  ["RASTRILLO D30", "Rastrillo Pulper D30", "PULPERS"],
  ["RASTRILLO E20", "Rastrillo Pulper E20", "PULPERS"],
  ["RASTRILLO E21", "Rastrillo Pulper E21", "PULPERS"],
  ["RASTRILLO E22", "Rastrillo Pulper E22", "PULPERS"],
  ["REG.TROMMEL D30", "Regadera Trommel Pulper D30", "PULPERS"],
  ["REG.TROMMEL E20", "Regadera Trommel Pulper E20", "PULPERS"],
  ["REG.TROMMEL E22", "Regadera Trommel Pulper E22", "PULPERS"],
  ["ROSCADOSIFIC-ASPRAY", "Rosca Dosificadora Almidón Spray", "PULPERS"],
  ["ROSCATRANS-ASPRAY", "Rosca Transportadora Almidón Spray", "PULPERS"],
  ["ROTOR PULPER D30", "Rotor Pulper D30", "PULPERS"],
  ["SACASAN 2", "Sac-A-San 2 - DP210 (Pulper D30)", "PULPERS"],
  ["DRV111", "Variador Cuchara Almidón (BOX A6.00.09)", "PULPERS"],
  ["VENT-E22", "Ventilador extractor pulper E22", "PULPERS"],
  ["VENT-E21", "Ventilador motor rotor pulper E21", "PULPERS"],
  ["VENTMR-E22", "Ventilador motor rotor pulper E22", "PULPERS"],
  ["APA.CARRETILLA", "Aparejo 1T Sala Carga Baterias", "SECADORES"],
  ["BO12DA", "Bomba 1 aceite lubricación 2da y 3ra. Bateria", "SECADORES"],
  ["BO14TA", "Bomba 1 aceite lubricación 4ta y 5ta. Bateria", "SECADORES"],
  ["BO11RA", "Bomba 1 aceite lubricación1ra. Bateria", "SECADORES"],
  ["BO22DA", "Bomba 2 aceite lubricación 2da y 3ra. Bateria", "SECADORES"],
  ["BO24TA", "Bomba 2 aceite lubricación 4ta y 5ta. Bateria", "SECADORES"],
  ["BO21RA", "Bomba 2 aceite lubricación1ra. Bateria", "SECADORES"],
  ["AGRE.BOACH5TA", "Bomba Achique Sótano 5ta bateria", "SECADORES"],
  ["CUCH1SUPMONO", "Cuchilla 1 Sup. Monolucido", "SECADORES"],
  ["CUCH2INTMONO", "Cuchilla 2 Int. Monolucido", "SECADORES"],
  ["CUCH3INFMONO", "Cuchilla 3 Inf. Monolucido", "SECADORES"],
  ["CUCH.SEC", "Cuchillas Secadores (Todas)", "SECADORES"],
  ["INT.AC1Y2", "Intercambiador Aire Caliente 1º / 2º Bateria", "SECADORES"],
  ["INT.AC3BAT", "Intercambiador Aire Caliente 3º Bateria", "SECADORES"],
  ["INT.AC4Y5", "Intercambiador Aire Caliente Sup 4º / 5º Bateria", "SECADORES"],
  ["MONO.INTREC1", "Intercambiador Recirculación 1 Monolucido", "SECADORES"],
  ["MONO.INTREC2", "Intercambiador Recirculación 2 Monolucido", "SECADORES"],
  ["MONO.MAUX", "Mando Auxiliar Monolucido", "SECADORES"],
  ["MAN.M1I1", "Mando M1I1 Rollo Tela Inf., Pos. 10-02, 1º Batería", "SECADORES"],
  ["MAN.M1I2", "Mando M1I2 Rollo Tela Inf., Pos. 10-04, 1º Bateria", "SECADORES"],
  ["MAN.M1I3", "Mando M1I3 Rollo Tela Inf., Pos. 10-07, 1º Bateria", "SECADORES"],
  ["MAN.M1S1", "Mando M1S1 Rollo Tela Sup., Pos. 10-02B, 1º Bateria", "SECADORES"],
  ["MAN.M1S2", "Mando M1S2 Rollo Tela Sup., Pos. 10-08, 1º Bateria", "SECADORES"],
  ["MAN.M1S3", "Mando M1S3 Rollo Tela Sup., Pos. 11-00, 1º Bateria", "SECADORES"],
  ["MAN.M1S4", "Mando M1S4 Secador 2 1ra. Bateria Cup", "SECADORES"],
  ["MAN.M2I1", "Mando M2I1 Rollo Tela Inf., Pos. 20-02, 2º Bateria", "SECADORES"],
  ["MAN.M2I2", "Mando M2I2 Rollo Tela Inf., Pos. 20-06, 2º Bateria", "SECADORES"],
  ["MAN.M2I3", "Mando M2I3 Rollo Tela Inf., Pos. 20-09, 2º Bateria", "SECADORES"],
  ["MAN.M2S1", "Mando M2S1 Rollo Tela Sup., Pos. 20-05, 2º Bateria", "SECADORES"],
  ["MAN.M2S2", "Mando M2S2 Rollo Tela Sup., Pos. 20-10, 2º Bateria", "SECADORES"],
  ["MAN.M3I1", "Mando M3I1 Rollo Tela Inf., Pos. 30-02, 3º Bateria", "SECADORES"],
  ["MAN.M3I2", "Mando M3I2 Rollo Tela Inf., Pos. 30-06, 3º Bateria", "SECADORES"],
  ["MAN.M3I3", "Mando M3I3 Rollo Tela Inf., Pos. 30-09, 3º Bateria", "SECADORES"],
  ["MAN.M3S1", "Mando M3S1 Rollo Tela Sup., Pos. 30-03, 3º Bateria", "SECADORES"],
  ["MAN.M3S2", "Mando M3S2 Rollo Tela Sup., Pos. 30-08, 3º Bateria", "SECADORES"],
  ["MAN.M4I1", "Mando M4i1 Mando Rollo Tela Inf., Pos. 40-01, 4ta. Bateria", "SECADORES"],
  ["MAN.M4I2", "Mando M4i2 Mando Rollo Tela Inf., Pos. 40-05, 4ta. Bateria", "SECADORES"],
  ["MAN.M4I3", "Mando M4i3 Mando Rollo Tela Inf., Pos. 40-08, 4ta. Bateria", "SECADORES"],
  ["MAN.M4S1", "Mando M4S1 Mando Rollo Tela Sup., Pos. 40-02, 4ta. Bateria", "SECADORES"],
  ["MAN.M4S2", "Mando M4S2 Mando Rollo Tela Sup., Pos. 41-02, 4ta. Bateria", "SECADORES"],
  ["MAN.M4S3", "Mando M4S3 Mando Rollo Tela Sup., Pos. 40-09, 4ta. Bateria", "SECADORES"],
  ["MAN.M5I1", "Mando M5i1 Mando Rollo Tela Inf., Pos. 50-01, 5ta. Bateria", "SECADORES"],
  ["MAN.M5I2", "Mando M5i2 Mando Rollo Tela Inf., Pos. 50-03, 5ta. Bateria", "SECADORES"],
  ["MAN.M5S1", "Mando M5S1 Mando Rollo Tela Sup., Pos. 50-02, 5ta. Bateria", "SECADORES"],
  ["MAN.M5S2", "Mando M5S2 Mando Rollo Tela Sup., Pos. 51-02, 5ta. Bateria", "SECADORES"],
  ["MONO.MAPPAL", "Mando MMNO Mando Principal Monolucido", "SECADORES"],
  ["MAN.ME6BT", "Mando Rollo Tela, Pos 61-03, 6º Batería (ME6BC)", "SECADORES"],
  ["MANBATERIA 6", "Mando Rollo Tela, Pos 61-04, 6º Batería", "SECADORES"],
  ["MANDOS PRESECADO", "Mandos batería presecado.M1S1/4-M2S1/2-M2I1/3-3I1/3-3S1/2", "SECADORES"],
  ["MANDOS POST SECADO", "Mandos Post Secado. (M411-M412-M413-MS1-MS2-MS3)", "SECADORES"],
  ["LUG.SEC.MONO", "Monolúcido (general)", "SECADORES"],
  ["LUG.SEC.BAT1", "Secadores 1ª batería (1 al 12)", "SECADORES"],
  ["LUG.SEC.BAT2", "Secadores 2ª batería (13 al 24)", "SECADORES"],
  ["LUG.SEC.BAT3", "Secadores 3ª batería (25 al 35)", "SECADORES"],
  ["LUG.SEC.BAT4", "Secadores 4ª batería (36 al 43)", "SECADORES"],
  ["LUG.SEC.BAT5", "Secadores 5ª batería (44 al 53)", "SECADORES"],
  ["MANB.VE1MOPRE", "Ventilador 1 Enfriamiento Motores Mando 1ra, 2da y 3ra Bateria", "SECADORES"],
  ["MANB.VE1MO", "Ventilador 1 Enfriamiento Motores Mando 4ta y 5ta Bateria", "SECADORES"],
  ["MANB.VE2MOPRE", "Ventilador 2 Enfriamiento Motores Mando 1ra, 2da y 3ra Bateria", "SECADORES"],
  ["MANB.VE2MO", "Ventilador 2 Enfriamiento Motores Mando 4ta y 5ta Bateria", "SECADORES"],
  ["DRV076", "Ventilador 2da bateria.(BOX 29.27.1B)", "SECADORES"],
  ["SECA.VEEXCA1", "Ventilador Extractor Capota 1RA Bateria", "SECADORES"],
  ["SECA.VEEXCA2", "Ventilador Extractor Capota 2DA Bateria", "SECADORES"],
  ["SECA.VEEXCA3", "Ventilador Extractor Capota 3RA Bateria", "SECADORES"],
  ["SECA.VEEXC4Y5", "Ventilador Extractor Capota 4º y 5º Bateria", "SECADORES"],
  ["EFLS.ADEN", "Adensador TSE", "SERVICIOS AUXILIARES"],
  ["AGIT-EFLS.POLI", "Agitacion Tanque Agente Retención TSE", "SERVICIOS AUXILIARES"],
  ["AGIT-EFLS.FLOC", "Agitacion Tanque Floculante TSE", "SERVICIOS AUXILIARES"],
  ["AGIT-EFLS.TQREACC", "Agitador Tanque Reacción Contipress TSE", "SERVICIOS AUXILIARES"],
  ["AGIT-CELL.TQSODA", "Agitador Tanque Soda Caldera", "SERVICIOS AUXILIARES"],
  ["AGIT-EFLS.TQUREA", "Agitador Tanque Urea TSE", "SERVICIOS AUXILIARES"],
  ["EFLS.AEREE1", "Aireador AE1 Pileta Aireación TSE", "SERVICIOS AUXILIARES"],
  ["EFLS.AEREE3", "Aireador AE3 Pileta Aireación TSE", "SERVICIOS AUXILIARES"],
  ["APA.450EFLU", "Aparejo Tanque 450m3 Efluentes", "SERVICIOS AUXILIARES"],
  ["TQE.BO1", "Bomba 1 Elevación Agua", "SERVICIOS AUXILIARES"],
  ["CA-BOCITD1", "Bomba 1 Fuel Oil a Tanque Diario", "SERVICIOS AUXILIARES"],
  ["TQE.BO2", "Bomba 2 Elevación Agua", "SERVICIOS AUXILIARES"],
  ["CA-BOCITD2", "Bomba 2 Fuel Oil a Tanque Diario", "SERVICIOS AUXILIARES"],
  ["CAKE.BO501", "Bomba 501 Alimentación Agua Caldera 1", "SERVICIOS AUXILIARES"],
  ["CAKE.BO502", "Bomba 502 Alimentación Agua Caldera 1", "SERVICIOS AUXILIARES"],
  ["CASA.BO503", "Bomba 503 Alimentación Agua Caldera 2", "SERVICIOS AUXILIARES"],
  ["CASA.BO504", "Bomba 504 Alimentación Agua Caldera 2 o 3", "SERVICIOS AUXILIARES"],
  ["TRAG.BO505", "Bomba 505 Descarbonatadora Calderas", "SERVICIOS AUXILIARES"],
  ["TRAG.BO506", "Bomba 506 Descarbonatadora Calderas", "SERVICIOS AUXILIARES"],
  ["TRAG.BO507", "Bomba 507 Agua Alimentación a Torres", "SERVICIOS AUXILIARES"],
  ["TRAG.BO508", "Bomba 508 Agua Alimentación a Torres", "SERVICIOS AUXILIARES"],
  ["VCDS.BOCD509", "Bomba 509 Desaireador Calderas", "SERVICIOS AUXILIARES"],
  ["VCDS.BOCD510", "Bomba 510 Desaireador Calderas", "SERVICIOS AUXILIARES"],
  ["CAGO.BO511", "Bomba 511 Alimentación Agua Caldera 3", "SERVICIOS AUXILIARES"],
  ["AGRE.BOACHEFL", "Bomba Achique Pozo Bombas Efluentes", "SERVICIOS AUXILIARES"],
  ["EFLS.BOACFOS", "Bomba Acido Fosfórico 1 TSE", "SERVICIOS AUXILIARES"],
  ["EFLS.BOACFOSA", "Bomba Acido Fosfórico 2 TSE", "SERVICIOS AUXILIARES"],
  ["EFLS.BLAV", "Bomba Agua Lavado Contipress TSE", "SERVICIOS AUXILIARES"],
  ["EFLS.BOREDPIA", "Bomba BS01 Lodos Sedimentador - TSE", "SERVICIOS AUXILIARES"],
  ["EFLS.BOREDPIA2", "Bomba BS02 Lodos Sedimentador - TSE", "SERVICIOS AUXILIARES"],
  ["EFLS.BOPILALM3", "Bomba BS03 Pileta Almacenamiento - TSE", "SERVICIOS AUXILIARES"],
  ["QUI-BODOSO1", "Bomba Dosific Soda Cáustica 1 Tratamiento Agua Caldera", "SERVICIOS AUXILIARES"],
  ["BOMB-DOS-ANTITSE", "Bomba dosificadora antiespumante TSE", "SERVICIOS AUXILIARES"],
  ["BODOCANPARS", "Bomba dosificadora Cloro Canal Parshall TSE", "SERVICIOS AUXILIARES"],
  ["QUI-BODOSOCA", "Bomba Dosificadora Soda Agua Alimentación Caldera", "SERVICIOS AUXILIARES"],
  ["QUI-BODOTRI", "Bomba Dosificadora TRIACT Caldera", "SERVICIOS AUXILIARES"],
  ["CA-BOTQRFO1", "Bomba Envío Fuel Oil a Tanque Reserva", "SERVICIOS AUXILIARES"],
  ["BOMGOIL.GEN", "Bomba Gas Oil Carga del Generador 1100", "SERVICIOS AUXILIARES"],
  ["CA-BOGAOIO1", "Bomba Gas Oil Sistema Descarga Fuel Oil", "SERVICIOS AUXILIARES"],
  ["EFLS.BOHIPO", "Bomba Hipoclorito TSE", "SERVICIOS AUXILIARES"],
  ["TSE.BPL", "Bomba Pileta Lodos TSE", "SERVICIOS AUXILIARES"],
  ["EFLS.BOPOLI", "Bomba Polimyn TSE", "SERVICIOS AUXILIARES"],
  ["BOSU.BOPO1", "Bomba Pozo 1", "SERVICIOS AUXILIARES"],
  ["BOSU.BOPO2", "Bomba Pozo 2", "SERVICIOS AUXILIARES"],
  ["BOSU.BOPO3", "Bomba Pozo 3", "SERVICIOS AUXILIARES"],
  ["BOSU.BOPO4", "Bomba Pozo 4", "SERVICIOS AUXILIARES"],
  ["BOSU.BOPO5", "Bomba Pozo 5", "SERVICIOS AUXILIARES"],
  ["BOSU.BOPO6", "Bomba Pozo 6", "SERVICIOS AUXILIARES"],
  ["TSE.BPETSE", "Bomba Presurizadora agua Edificio TSE", "SERVICIOS AUXILIARES"],
  ["BBAREGEMECAN", "Bomba Regadera Prensa Emecan TSE", "SERVICIOS AUXILIARES"],
  ["QUI-BODOSODES", "Bomba Soda a descarbonatadora", "SERVICIOS AUXILIARES"],
  ["DRV027", "Bomba Tanque 450 Efluentes (BOX 2A.04.05)", "SERVICIOS AUXILIARES"],
  ["BOMB-EFLS.POLI", "Bomba Tanque Agente Retención TSE", "SERVICIOS AUXILIARES"],
  ["EFLS.BFLOC", "Bomba Tanque Floculante TSE Contipress", "SERVICIOS AUXILIARES"],
  ["EFLS.BFLOCE", "Bomba Tanque Floculante TSE Emecan", "SERVICIOS AUXILIARES"],
  ["BOMB-BOSU.TQIPO3/6", "Bomba Tanque Intermedio Pozo 3 y 6", "SERVICIOS AUXILIARES"],
  ["BOMB-BOSU.TQIPO4/5", "Bomba Tanque Intermedio Pozo 4 y 5", "SERVICIOS AUXILIARES"],
  ["BOMB-CAL.TQPA", "Bomba Tanque Preparación Acido Sulfúrico Calderas", "SERVICIOS AUXILIARES"],
  ["BOMB-EFLS.TQREACC", "Bomba Tanque Reacción Contipress TSE", "SERVICIOS AUXILIARES"],
  ["BOMB-TRAG.TQSODA", "Bomba Tanque Soda Caldera", "SERVICIOS AUXILIARES"],
  ["BOMB-EFLS.TQUREA", "Bomba Tanque Urea TSE", "SERVICIOS AUXILIARES"],
  ["DRV136", "Bomba TQ Intermediario Pozo 3 y 6 (Box )", "SERVICIOS AUXILIARES"],
  ["LUG.SSAA.CALDERA4", "Caldera 4", "SERVICIOS AUXILIARES"],
  ["EFLS.CINTALO", "Cinta Longitudinal Lodos TSE", "SERVICIOS AUXILIARES"],
  ["COM-KAESER.CK1", "Compresor Kaeser CK1", "SERVICIOS AUXILIARES"],
  ["COM-SULLAIR.CS1", "Compresor Sullair CS1", "SERVICIOS AUXILIARES"],
  ["COM-SULLAIR.CS2", "Compresor Sullair CS2", "SERVICIOS AUXILIARES"],
  ["EFLS.CONT", "Contipress TSE", "SERVICIOS AUXILIARES"],
  ["EFLS.DECAN", "Decantador TSE", "SERVICIOS AUXILIARES"],
  ["CAKE.DESAE", "Desaireador Agua Calderas", "SERVICIOS AUXILIARES"],
  ["EAF4 WESTRIC", "Equipo agua fria 4 Westric", "SERVICIOS AUXILIARES"],
  ["INST-GRAL", "Instalaciones generales", "SERVICIOS AUXILIARES"],
  ["EFLS.MEZCLA", "Mezclador AE2 Pileta Aireación TSE", "SERVICIOS AUXILIARES"],
  ["MIXER.FLOC", "Mixer preparacion Floculante TSE", "SERVICIOS AUXILIARES"],
  ["LUG.SSAA.GAS", "Planta de Gas / GLP", "SERVICIOS AUXILIARES"],
  ["LUG.SSAA.FUELOIL", "Planta Fuel Oil", "SERVICIOS AUXILIARES"],
  ["EFLS.PRENLO", "Prensa Emecan TSE", "SERVICIOS AUXILIARES"],
  ["EFLS.SOPAERO", "Soplador Pileta Aireación TSE", "SERVICIOS AUXILIARES"],
  ["EFLS.SOPCLO", "Soplador Pileta Cloracion TSE", "SERVICIOS AUXILIARES"],
  ["EFLS.TORNILLO", "Tornillo Sinfin Lodos TSE", "SERVICIOS AUXILIARES"],
  ["VENT-SULLAIR.CS1", "Ventilador Radiador Compresor Sullair CS1", "SERVICIOS AUXILIARES"],
  ["VENT-SULLAIR.CS2", "Ventilador Radiador Compresor Sullair CS2", "SERVICIOS AUXILIARES"],
  ["VENT.TQ.DESCARB", "Ventilador Tanque Descarbonatadora", "SERVICIOS AUXILIARES"],
  ["CAKE.VENTIFOR", "Ventilador Tiro Forzado Caldera 1", "SERVICIOS AUXILIARES"],
  ["CASA.VENTIFOR", "Ventilador Tiro Forzado Caldera 2", "SERVICIOS AUXILIARES"],
  ["CAGO.VENTIFOR", "Ventilador Tiro Forzado Caldera 3", "SERVICIOS AUXILIARES"],
  ["BOMB-TREA.I", "Bomba Tanque Recupero Agua CI", "SEXTA BATERIA"],
  ["CUINFCAL2", "Cuchilla inferior Calandra 2", "SEXTA BATERIA"],
  ["CT2.M20MAN", "Mando M20 Cilindro Tiro 2", "SEXTA BATERIA"],
  ["CAL2.MAN", "Mando Rollo Calandra 2 (MECN2)", "SEXTA BATERIA"],
  ["POPECAL2.SO", "Mando Soga Calandra 2 y Pope (MESG4)", "SEXTA BATERIA"],
  ["AGUJCHICA", "Agujereadora de Banco (Chica)", "TALLERES"],
  ["AGUJGRANDE", "Agujereadora de Banco GSP (Grande)", "TALLERES"],
  ["GRUA.ELEVPAÑ", "Aparejo 1T Pañol", "TALLERES"],
  ["GRUA.CARTTEE1", "Aparejo 1T Taller Eléctrico", "TALLERES"],
  ["GRUA.ELEVTEE2", "Aparejo 3T Taller Eléctrico", "TALLERES"],
  ["GRUA.CARTTEE2", "Aparejo 500 kg Taller Eléctrico", "TALLERES"],
  ["GRUA.ELEVAUTEL", "Aparejo 5T Taller Autoelevadores", "TALLERES"],
  ["GRUA.CARTTM", "Aparejo Exterior Taller Mecánico", "TALLERES"],
  ["BOMGOIL.AUT", "Bomba Gas Oil Carga Autoelevadores", "TALLERES"],
  ["LIMADORA", "Limadora Furlanetto", "TALLERES"],
  ["GRUA.ELEVCPTM", "Puente Grúa 3T. Taller Mecánico", "TALLERES"],
  ["SIERRA CARPINTERIA", "Sierra circular Carpinteria", "TALLERES"],
  ["LUG.TALL.ELECTRICO", "Taller Eléctrico (general)", "TALLERES"],
  ["TORNOALFA", "Torno Paralelo Alfa (Chico)", "TALLERES"],
  ["TORNOPIA", "Torno Paralelo PIA (Grande)", "TALLERES"],
  ["TORNOSANTOSVEGA", "Torno Paralelo Santos Vega (Mediano)", "TALLERES"],
  ["TACA.VEEXPOL", "Ventilador Extractor Polvillo Carpinteria", "TALLERES"],
  ["DRV099", "Bomba 1 tanque agua a clarificar (BOX A6.03)", "TAP"],
  ["BO1.TQAC-TAP", "Bomba 1 Tanque Agua Clarificada - TQ243 y TQ260", "TAP"],
  ["BO1.TQAF-TAP", "Bomba 1 Tanque Agua Filtrada - Pulpo CI", "TAP"],
  ["DRV001", "Bomba 1 Tq Agua Filtrada - PULPO C.I. (BOX A6.03)", "TAP"],
  ["BO2.TQAAC-TAP", "Bomba 2 Tanque Agua a Clarificar - Deltafloat", "TAP"],
  ["BO2.TQAC-TAP", "Bomba 2 Tanque Agua Clarificada - Sigmafilter", "TAP"],
  ["BO2.TQAF-TAP", "Bomba 2 Tanque Agua Filtrada - Fibernet", "TAP"],
  ["BO.TDA-TAP", "Bomba aporte ADT - TAP", "TAP"],
  ["AGRE.BOBD3M", "Bomba Bandeja 3M", "TAP"],
  ["BOMB-DOS-ANTIMESAS", "Bomba dosificadora antiespumante p/preparacion", "TAP"],
  ["DRV135", "Bomba Nivel TQ 1,5 m3 Agua Fria Sotano (Box 21.08)", "TAP"],
  ["BOMB-TQ AGUA A CLARIF", "Bomba Tanque de agua a clarificar", "TAP"],
  ["BOMB-TQ AGUA FILTRADA", "Bomba Tanque de agua filtrada", "TAP"],
  ["DF 47", "Deltafloat DF 47", "TAP"],
  ["DRV124", "Variador Cuchara DF47 (BOX A6.xx)", "TAP"],
  ["AGIT-PIL231", "Agitacion Tanque 231", "TEC MAULE PTA BAJA"],
  ["AGIT-QUI-TQ1AE", "Agitador Tanque 1 Antiespumante", "TEC MAULE PTA BAJA"],
  ["AGIT-QUI-TQ2AE", "Agitador Tanque 2 Antiespumante", "TEC MAULE PTA BAJA"],
  ["AGIT-TQ 230", "Agitador Tanque 230", "TEC MAULE PTA BAJA"],
  ["AGIT-TQ 241", "Agitador Tanque 241", "TEC MAULE PTA BAJA"],
  ["AGIT-TQ 243", "Agitador Tanque 243", "TEC MAULE PTA BAJA"],
  ["AGIT-TQ 260", "Agitador Tanque 260", "TEC MAULE PTA BAJA"],
  ["AGIT-TQ 50 M3 TETRA", "Agitador Tanque 50 m3 Tetra y CTMP", "TEC MAULE PTA BAJA"],
  ["AGTINA 250", "Agitador Tanque Tina 250", "TEC MAULE PTA BAJA"],
  ["MD.BORES", "Bomba 1 Recirculacion Dorso", "TEC MAULE PTA BAJA"],
  ["BO1.TQAAC-TAP", "Bomba 1 Tanque Agua a Clarificar - A TAC", "TEC MAULE PTA BAJA"],
  ["MD.BORES2", "Bomba 2 Recirculacion Dorso", "TEC MAULE PTA BAJA"],
  ["DRV002", "Bomba 3 Tanque agua circulante (BOX A6.00.05)", "TEC MAULE PTA BAJA"],
  ["TECI.BODIDI", "Bomba Agua Dilucion 1", "TEC MAULE PTA BAJA"],
  ["TAQI.BOACIST5", "Bomba Agua Dilucion 3 CI (A Tanque Recupero CI)", "TEC MAULE PTA BAJA"],
  ["PILI.2CDIBO", "Bomba Agua Dilucion 4 (a Tanque Recupero CI)", "TEC MAULE PTA BAJA"],
  ["DEPI.3ºBO", "Bomba Agua Dilucion N°6 (A Fracc 220 y DC240)", "TEC MAULE PTA BAJA"],
  ["BOMB-CNTQ 230", "Bomba control nivel Tanque 230", "TEC MAULE PTA BAJA"],
  ["DRV077", "Bomba dilucion distribuidor central 2.(BOX 29.27.09)", "TEC MAULE PTA BAJA"],
  ["DRV078", "Bomba Recir. Dorso.(BOX 29.27.09)", "TEC MAULE PTA BAJA"],
  ["BOMB-TQ 100 M3 DORSO", "Bomba Tanque 100 m3 de dorso", "TEC MAULE PTA BAJA"],
  ["BOMB-TQ 230", "Bomba tanque 230", "TEC MAULE PTA BAJA"],
  ["DRV004", "Bomba tanque 230 (BOX A6.00.04)", "TEC MAULE PTA BAJA"],
  ["BOMB-TQ 260", "Bomba Tanque 260", "TEC MAULE PTA BAJA"],
  ["DRV097", "Bomba tanque 260 (BOX 0A.03)", "TEC MAULE PTA BAJA"],
  ["MD.BOREC", "Bomba Tanque Agua Blanca Dorso", "TEC MAULE PTA BAJA"],
  ["BOMB-TQ H2O CIR CI", "Bomba Tanque agua circulante capa intermedia", "TEC MAULE PTA BAJA"],
  ["BOMB-PIL H2O CIR CUP", "Bomba Tanque de agua circulante cupertina", "TEC MAULE PTA BAJA"],
  ["DRV093", "Bomba tanque rebalse agua depur. (BOX 04.08)", "TEC MAULE PTA BAJA"],
  ["BOMB-TRECIRCI", "Bomba Tanque Recirculación CI", "TEC MAULE PTA BAJA"],
  ["BOMTINA250", "Bomba Tina 250", "TEC MAULE PTA BAJA"],
  ["DILI.DEZTINAM", "Dezurik Tina 250", "TEC MAULE PTA BAJA"],
  ["AGIT-T200C", "Agitador Tanque 200 Corte", "TQ 200 CORTE"],
  ["AGIT-TQ200 D30", "Agitador Tanque 200 D30", "TQ 200 CORTE"],
  ["BOMB-T200C", "Bomba Tanque 200 Corte 1° Nivel", "TQ 200 CORTE"],
  ["BOMB-T200C2°N", "Bomba Tanque 200 Corte 2° Nivel", "TQ 200 CORTE"],
  ["CAMIONETAFORD", "Camioneta Ford Ranger", "VEHICULOS"],
  ["CAMIONETATOYOTA", "Camioneta Toyota Hilux", "VEHICULOS"],
  ["DRV055", "Extractor de aire Quick Draft(BOX 90.0C.07)", "VENTILADORES Y EXTRACTORES"],
  ["EXTCENTROTORTAS", "Extractor de centros de tortas de bobinas", "VENTILADORES Y EXTRACTORES"],
  ["INT.ACINFPRE", "Intercambiador Aire Caliente Inf Presecado", "VENTILADORES Y EXTRACTORES"],
  ["RUB-VECO", "Ventilador Aire Combustión Generador Aire Caliente Rubcar", "VENTILADORES Y EXTRACTORES"],
  ["RUB-VERE", "Ventilador Aire Recirculación Generador Aire Caliente Rubcar", "VENTILADORES Y EXTRACTORES"],
  ["VENT.AUXST", "Ventilador axial sala de tableros Principal", "VENTILADORES Y EXTRACTORES"],
  ["TF.VENANTINIE", "Ventilador Caja Antiniebla Top Former", "VENTILADORES Y EXTRACTORES"],
  ["VENT-PRESALA", "Ventilador centrifugo sala de tableros principal", "VENTILADORES Y EXTRACTORES"],
  ["VENT-EQA", "Ventilador combustión EQA", "VENTILADORES Y EXTRACTORES"],
  ["VENTIRLS+VB", "Ventilador combustión IR Labio Soplado + Varibar", "VENTILADORES Y EXTRACTORES"],
  ["VENTEXTPARA", "Ventilador extractor 1 Parabólico", "VENTILADORES Y EXTRACTORES"],
  ["VENTEXTPARA2", "Ventilador extractor 2 Parabólico", "VENTILADORES Y EXTRACTORES"],
  ["MONO.VEEX", "Ventilador Extractor Capota Monolucido", "VENTILADORES Y EXTRACTORES"],
  ["CELL.VEEXPOC2", "Ventilador Extractor Polvillo Cocinador C2", "VENTILADORES Y EXTRACTORES"],
  ["VEMOVAR.UNI", "Ventilador Motor Varilla Unibar", "VENTILADORES Y EXTRACTORES"],
  ["VEMOVAR.VARI", "Ventilador Motor Varilla Varibar", "VENTILADORES Y EXTRACTORES"],
  ["LABS.VENC01", "Ventilador NC01", "VENTILADORES Y EXTRACTORES"],
  ["SUB2.TR01VENT2", "Ventilador N°2 Transformador Potencia N°1 S.E N°2", "VENTILADORES Y EXTRACTORES"],
  ["VENT-TABPBM", "Ventilador Presurización Tablero Varidur / PBM", "VENTILADORES Y EXTRACTORES"],
  ["VENTIRVB", "Ventilador recirculación IR Varibar", "VENTILADORES Y EXTRACTORES"],
  ["VENT-SESTUC", "Ventilador Sala de Tableros Estucado", "VENTILADORES Y EXTRACTORES"],
  ["AUX.VEVF", "Ventilador Vacuum Foil Auxiliar", "VENTILADORES Y EXTRACTORES"],
];
const MAPEO_ARBOL_VIEJO = {
  "SERVICIOS AUXILIARES|BOMBAS AGUA POZO|BOMBA POZO 1": "BOSU.BOPO1",
  "SERVICIOS AUXILIARES|BOMBAS AGUA POZO|BOMBA POZO 2": "BOSU.BOPO2",
  "SERVICIOS AUXILIARES|BOMBAS AGUA POZO|BOMBA POZO 3": "BOSU.BOPO3",
  "SERVICIOS AUXILIARES|BOMBAS AGUA POZO|BOMBA POZO 4": "BOSU.BOPO4",
  "SERVICIOS AUXILIARES|BOMBAS AGUA POZO|BOMBA POZO 5": "BOSU.BOPO5",
  "SERVICIOS AUXILIARES|BOMBAS AGUA POZO|BOMBA POZO 6": "BOSU.BOPO6",
  "SERVICIOS AUXILIARES|TRATAMIENTO DE AGUA CALDERAS|": "CAKE.DESAE",
  "SERVICIOS AUXILIARES|TRATAMIENTO DE AGUA CALDERAS|BOMBA AGUA 505 DESCARBONATADORA CALDERAS": "TRAG.BO505",
  "SERVICIOS AUXILIARES|TRATAMIENTO DE AGUA CALDERAS|BOMBA AGUA 506 DESCARBONATADORA CALDERAS": "TRAG.BO506",
  "SERVICIOS AUXILIARES|TRATAMIENTO DE AGUA CALDERAS|BOMBA AGUA 507 ALIMENTACION TORRES CALDERAS": "TRAG.BO507",
  "SERVICIOS AUXILIARES|TRATAMIENTO DE AGUA CALDERAS|BOMBA AGUA 508 ALIMENTACION TORRES CALDERAS": "TRAG.BO508",
  "SERVICIOS AUXILIARES|TRATAMIENTO DE AGUA CALDERAS|BOMBA 509 DESAIREADOR CALDERAS": "VCDS.BOCD509",
  "SERVICIOS AUXILIARES|TRATAMIENTO DE AGUA CALDERAS|BOMBA 510 DESAIREADOR CALDERAS": "VCDS.BOCD510",
  "SERVICIOS AUXILIARES|TRATAMIENTO EFLUENTES SECUNDARIO|BOMBA BS01 LODOS SEDIMENTADOR TSE": "EFLS.BOREDPIA",
  "SERVICIOS AUXILIARES|TRATAMIENTO EFLUENTES SECUNDARIO|BOMBA BS02 LODOS SEDIMENTADOR TSE": "EFLS.BOREDPIA2",
  "SERVICIOS AUXILIARES|TRATAMIENTO EFLUENTES SECUNDARIO|PRENSA EMECAN TSE": "EFLS.PRENLO",
  "SERVICIOS AUXILIARES|TRATAMIENTO EFLUENTES SECUNDARIO|CINTA DE LODOS TSE LONGITUDINAL": "EFLS.CINTALO",
  "SERVICIOS AUXILIARES|TRATAMIENTO EFLUENTES SECUNDARIO|BOMBA PILETA LODOS TSE": "TSE.BPL",
  "SERVICIOS AUXILIARES|TRATAMIENTO EFLUENTES SECUNDARIO|AGITADOR TQ UREA TSE": "AGIT-EFLS.TQUREA",
  "SERVICIOS AUXILIARES|TRATAMIENTO EFLUENTES SECUNDARIO|BOMBA TQ UREA TSE": "BOMB-EFLS.TQUREA",
  "SERVICIOS AUXILIARES|TRATAMIENTO EFLUENTES SECUNDARIO|BOMBA TQ FLOCULANTE TSE": "EFLS.BFLOC",
  "SERVICIOS AUXILIARES|TRATAMIENTO EFLUENTES SECUNDARIO|SOPLADOR PILETA REACTIVACION TSE": "EFLS.SOPAERO",
  "SERVICIOS AUXILIARES|TRATAMIENTO EFLUENTES SECUNDARIO|BOMBA REGADERA PRENSA EMECAN TSE": "BBAREGEMECAN",
  "SERVICIOS AUXILIARES|TRATAMIENTO EFLUENTES SECUNDARIO|DECANTADOR SECUNDARIO TSE": "EFLS.DECAN",
  "SERVICIOS AUXILIARES|TRATAMIENTO EFLUENTES SECUNDARIO|SOPLADOR PIL AIREACION TSE": "EFLS.SOPAERO",
  "SERVICIOS AUXILIARES|TRATAMIENTO EFLUENTES SECUNDARIO|SOPLADOR PIL CLORACION TSE": "EFLS.SOPCLO",
  "SERVICIOS AUXILIARES|TRATAMIENTO EFLUENTES SECUNDARIO|CONTIPRESS": "EFLS.CONT",
  "SERVICIOS AUXILIARES|CALDERA 4|BOMBA AGUA 501 ALIMENTACION CALDERA 4": "CAKE.BO501",
  "SERVICIOS AUXILIARES|CALDERA 4|BOMBA AGUA 502 ALIMENTACION CALDERA 4": "CAKE.BO502",
  "SERVICIOS AUXILIARES|CALDERA 4|BOMBA FUEL OIL 1 CALDERA 4": "CA-BOCITD1",
  "SERVICIOS AUXILIARES|CALDERA 4|BOMBA FUEL OIL 2 CALDERA 4": "CA-BOCITD2",
  "SERVICIOS AUXILIARES|SALA COMPRESORES|COMPRESOR SULLAIR CS01": "COM-SULLAIR.CS1",
  "SERVICIOS AUXILIARES|SALA COMPRESORES|COMPRESOR SULLAIR CS02": "COM-SULLAIR.CS1",
  "SERVICIOS AUXILIARES|SALA COMPRESORES|COMPRESOR KAESER": "COM-KAESER.CK1",
  "PULPERS|PULPER D30|": "PULPER D30",
  "PULPERS|PULPER D30|PULPER D30": "PULPER D30",
  "PULPERS|PULPER D30|CINTA DE CARGA PULPER D30": "CINTA D30",
  "PULPERS|PULPER D30|TROMMEL PULPER D30": "REG.TROMMEL D30",
  "PULPERS|PULPER D30|FIBERIZER PULPER D30": "FIBERIZER D30",
  "PULPERS|PULPER D30|DEPURADOR 210 PULPER D30": "PULPER D30",
  "PULPERS|PULPER D30|SAC A SAN PULPER D30": "SACASAN 2",
  "PULPERS|PULPER D30|BOMBA PULPER D30": "BOMPULPER D30",
  "PULPERS|PULPER D30|BOMBA TQ 200 D30": "TAQI.BOACI201",
  "PULPERS|PULPER D30|AGITADOR TQ 200 D30": "AGIT-TQ200 D30",
  "PULPERS|PULPER E20|": "PULPER E20",
  "PULPERS|PULPER E20|PULPER E20": "PULPER E20",
  "PULPERS|PULPER E20|CINTA DE CARGA PULPER E20": "CINTA E20",
  "PULPERS|PULPER E20|TROMMEL PULPER E20": "REG.TROMMEL E20",
  "PULPERS|PULPER E20|FIBERIZER PULPER E20": "FIBERIZER E20",
  "PULPERS|PULPER E20|BOMBA PULPER E20": "BOMBPULPER E20",
  "PULPERS|PULPER E21|": "PULPER E21",
  "PULPERS|PULPER E21|PULPER E21": "PULPER E21",
  "PULPERS|PULPER E21|CINTA DE CARGA PULPER E21": "CINTA E21",
  "PULPERS|PULPER E21|BOMBA PULPER E21": "BOMPULPER E21",
  "PULPERS|PULPER E22|": "PULPER E22",
  "PULPERS|PULPER E22|PULPER E22": "PULPER E22",
  "PULPERS|PULPER E22|CINTA DE CARGA PULPER E22": "CINTA E22",
  "PULPERS|PULPER E22|TROMMEL PULPER E22": "REG.TROMMEL E22",
  "PULPERS|PULPER E22|BOMBA PULPER E22": "BOMPULPER E22",
  "PULPERS|ALMIDON PULPERS|": "AGIT-AP.TQA",
  "PULPERS|ALMIDON PULPERS|BOMBA TQ COCINADOR ALMIDON": "BOMB-AP.TQC",
  "PULPERS|ALMIDON PULPERS|BOMBA TQ ALMACENAMIENTO ALMIDON": "BOMB-AP.TQA",
  "PULPERS|ALMIDON PULPERS|AGITADOR TQ COCINADOR ALMIDON": "AGIT-AP.TQC",
  "PULPERS|ALMIDON PULPERS|AGITADOR TQ ALMACENAMIENTO ALMIDON": "AGIT-AP.TQA",
  "PLANTA DE PASTA|SECTOR REFINOS Y FIBERIZER|ZARANDA 102": "ZARC.102",
  "PLANTA DE PASTA|SECTOR REFINOS Y FIBERIZER|DEPURADOR V12 CI": "MI.V12",
  "PLANTA DE PASTA|SECTOR REFINOS Y FIBERIZER|FRACCIONADOR 220": "FRACC220",
  "PLANTA DE PASTA|TEC MAULE PLANTA ALTA|SEPARPLAST 231": "SEPARPLAST",
  "PLANTA DE PASTA|TEC MAULE PLANTA ALTA|SEPARPLAST 232": "SEPARTPLAST",
  "PLANTA DE PASTA|TEC MAULE PLANTA ALTA|ZARANDA SEPARPLAST": "ZARI.ZARSEPAR",
  "PLANTA DE PASTA|TEC MAULE PLANTA ALTA|BOMBA REGADERA SEPARPLAST": "TECI.RESEBO",
  "PLANTA DE PASTA|TEC MAULE PLANTA ALTA|TORNILLO ELEVACION TEC MAULE": "TECI.RET251",
  "PLANTA DE PASTA|TEC BLANES|FAN SEPARATOR": "FAN.SEPARATOR",
  "TEC MAULE PTA BAJA|TANQUE AGUA CIRCULANTE|": "BOMB-PIL H2O CIR CUP",
  "TEC MAULE PTA BAJA|TANQUE AGUA CIRCULANTE|BOMBA DILUCION 1 TAC": "TECI.BODIDI",
  "TEC MAULE PTA BAJA|TANQUE AGUA CIRCULANTE|BOMBA DILUCION 3 TAC": "TAQI.BOACIST5",
  "TEC MAULE PTA BAJA|TANQUE AGUA CIRCULANTE|BOMBA DILUCION 4 TAC": "PILI.2CDIBO",
  "TEC MAULE PTA BAJA|TANQUE AGUA CIRCULANTE|BOMBA DILUCION 6 TAC": "DEPI.3ºBO",
  "TEC MAULE PTA BAJA|TANQUE 230|": "AGIT-TQ 230",
  "TEC MAULE PTA BAJA|TANQUE 230|BOMBA TQ 230": "BOMB-TQ 230",
  "TEC MAULE PTA BAJA|TANQUE 230|AGITADOR TQ 230": "AGIT-TQ 230",
  "TEC MAULE PTA BAJA|TANQUE 250|": "AGTINA 250",
  "TEC MAULE PTA BAJA|TANQUE 250|BOMBA TQ 250": "BOMTINA250",
  "TEC MAULE PTA BAJA|TANQUE 250|AGITADOR TQ 250": "AGTINA 250",
  "TEC MAULE PTA BAJA|TANQUE 250|BOMBA RECIRCULACION TQ 250": "BOMTINA250",
  "TEC MAULE PTA BAJA|TANQUE 260|": "AGIT-TQ 260",
  "TEC MAULE PTA BAJA|TANQUE 260|BOMBA TQ 260": "BOMB-TQ 260",
  "TEC MAULE PTA BAJA|BOMBA TQ 100 DORSO|": "BOMB-TQ 100 M3 DORSO",
  "TAP|BOMBA ADT|": "BO.TDA-TAP",
  "TAP|BOMBA 1 TQ AGUA A CLARIFICAR - DELTAFLOAT|": "BO2.TQAAC-TAP",
  "TAP|BOMBA 1 TQ AGUA CLARIFICADA - TQ243 Y TQ260|": "BO1.TQAC-TAP",
  "TAP|BOMBA 1 TQ AGUA FILTRADA - PULPO CI|": "BO1.TQAF-TAP",
  "TAP|BOMBA 2 TQ AGUA A CLARIFICAR - TAC|": "BO2.TQAAC-TAP",
  "TAP|BOMBA 2 TQ AGUA CLARIFICADA - SIGMAFILTER|": "BO2.TQAC-TAP",
  "TAP|BOMBA 2 TQ AGUA FILTRADA - FIBERNET|": "BO2.TQAF-TAP",
  "PILETAS LM|PILETA 210|": "AGIT-PIL210I",
  "PILETAS LM|PILETA 210|BOMBA PIL 210": "BOMB-PIL210I",
  "PILETAS LM|PILETA 210|AGITADOR PIL 210": "AGIT-PIL210I",
  "PILETAS LM|PILETA 401|": "AGIT-PIL401",
  "PILETAS LM|PILETA 401|BOMBA PIL 401": "BOMB-PIL401",
  "PILETAS LM|PILETA 401|AGITADOR PIL 401": "AGIT-PIL401",
  "PILETAS LM|PILETA 101|": "AGIT-PIL101C",
  "PILETAS LM|PILETA 101|BOMBA PIL 101": "BOMB-PIL101C",
  "PILETAS LM|PILETA 101|AGITADOR PIL 101": "AGIT-PIL101C",
  "PILETAS LM|PILETA B|": "BOMB-PIL-B",
  "PILETAS LM|PILETA B|BOMBA PIL B": "BOMB-PIL-B",
  "PILETAS LM|BOMBA FILTROS RONNINGEN|": "ALIM.BORONN",
  "PILETAS LM|TANQUE ELEVACION|BOMBA 1 TQ ELEV": "BOMB-PIL-A",
  "PILETAS LM|TANQUE ELEVACION|BOMBA 2 TQ ELEV": "BOMB-PIL-A2",
  "PILETAS LM|BOMBA DEPURACION 1º CI|": "MI.BODP",
  "PILETAS LM|BOMBA DEPURACION 2º CI|": "MI.BODS",
  "PILETAS LM|BOMBA DEPURACION 3º CI|": "MI.BODT",
  "PILETAS LM|BOMBA TQ REBALSE DEP CI|": "BOMB-TQ REB AGUA DEP",
  "PILETAS LM|BOMBA PILETA AGUA CIRCULANTE|": "BOMB-TEC.TAC",
  "PILETAS LM|BOMBA AUXILIAR CELLIER|": "CELL.BOAGTANQ",
  "PILETAS LM|DEPURADOR V22 CI|": "MI.V22",
  "PILETAS LM|BOMBA FAN CI|": "MI.BOFAN",
  "PILETAS LM|BOMBA TANQUE 305|": "BO.TQ305",
  "PILETAS LM|BOMBA DEPURADOR DP2 CI|": "MI.BAV12",
  "PILETAS LC|PILETA 102|": "AGIT-PIL102C",
  "PILETAS LC|PILETA 102|AGITADOR PIL 102": "AGIT-PIL102C",
  "PILETAS LC|PILETA 270|": "AGIT-PIL270I",
  "PILETAS LC|PILETA 270|AGITADOR PIL 270": "AGIT-PIL270I",
  "PILETAS LC|PILETA 220|": "AGIT-PIL220I",
  "PILETAS LC|PILETA 220|BOMBA PIL 220": "BOMB-PIL220I",
  "PILETAS LC|PILETA 220|AGITADOR PIL 220": "AGIT-PIL220I",
  "PILETAS LC|PILETA 301|": "AGIT-PIL.301",
  "PILETAS LC|PILETA 301|BOMBA PIL 301": "BOMB-PIL.301",
  "PILETAS LC|PILETA 301|AGITADOR PIL 301": "AGIT-PIL.301",
  "PILETAS LC|PILETA 242|": "AGIT-PIL.242",
  "PILETAS LC|PILETA 242|BOMBA PIL 242": "BOMB-PIL.242",
  "PILETAS LC|PILETA 242|AGITADOR PIL 242": "AGIT-PIL.242",
  "PILETAS LC|PILETA 303|": "AGIT-PIL303D",
  "PILETAS LC|PILETA 303|BOMBA PIL 303": "BOMB-PIL303D",
  "PILETAS LC|PILETA 303|AGITADOR PIL 303": "AGIT-PIL303D",
  "PILETAS LC|PILETA 304|": "AGIT-PIL304D",
  "PILETAS LC|PILETA 304|BOMBA PIL 304": "BOMB-PIL304D",
  "PILETAS LC|PILETA 304|AGITADOR PIL 304": "AGIT-PIL304D",
  "PILETAS LC|PILETA 103|": "AGIT-PIL103C",
  "PILETAS LC|PILETA 103|BOMBA PIL 103": "BOMB-PIL103C",
  "PILETAS LC|PILETA 103|AGITADOR PIL 103": "AGIT-PIL103C",
  "PILETA AGUA CORTE|PILETA AGUA CORTE|": "BOMB-PIL AGUA CORTE",
  "PILETA AGUA CORTE|PILETA AGUA CORTE|BOMBA AGUA REFILE POZO COUCH - VARIDUR": "BOMREFPC",
  "PILETA AGUA CORTE|PILETA AGUA CORTE|BOMBA DILUCION PBM": "CICO.BOCOPBM",
  "PILETA AGUA CORTE|PILETA AGUA CORTE|BOMBA MEZCLA PIL AGUA CORTE": "PILAC.BOM",
  "PILETA AGUA CORTE|PILETA AGUA CORTE|BOMBA AGUA CORTE POZO COUCH": "CICO.BOAG",
  "TQ 200 CORTE|TANQUE 200 CORTE|": "AGIT-T200C",
  "TQ 200 CORTE|TANQUE 200 CORTE|BOMBA 1° NIVEL": "BOMB-T200C",
  "TQ 200 CORTE|TANQUE 200 CORTE|BOMBA 2° NIVEL": "BOMB-T200C2°N",
  "HIDROPOLIS|PLANTA ALTA|DENSIDISC 1": "DENSI1",
  "HIDROPOLIS|PLANTA ALTA|DENSIDISC 2": "DENSI2",
  "HIDROPOLIS|PLANTA ALTA|ZARANDA 204": "EFLU.ZAR204N1",
  "HIDROPOLIS|PLANTA ALTA|ZARANDA 205": "EFLU.ZAR205N2",
  "HIDROPOLIS|PLANTA ALTA|ZARANDA 206": "EFLU.ZAR206N3",
  "HIDROPOLIS|PILETA ACUMULADORA|": "AGIT-PIL ACUM",
  "HIDROPOLIS|PILETA ACUMULADORA|BOMBA PIL PASTA RECUPERADA": "BOMB-HID.PR",
  "HIDROPOLIS|PILETA ACUMULADORA|BOMBA TDA": "BO.ADT",
  "HIDROPOLIS|CANAL EFLUENTES|BOMBA EFLUENTES TITULAR": "EFLU.BOAUX3",
  "HIDROPOLIS|CANAL EFLUENTES|BOMBA EFLUENTES 3": "EFLU.BOAUX3",
  "HIDROPOLIS|CANAL EFLUENTES|BOMBA SEDIFLOAT 1": "EFLU.BOSDF1",
  "HIDROPOLIS|CANAL EFLUENTES|BOMBA SEDIFLOAT 2": "EFLU.BOSDF2",
  "HIDROPOLIS|TANQUE 450 EFLUENTES|": "AGIT-TQ 450 EFLUENTES",
  "HIDROPOLIS|TANQUE 450 EFLUENTES|BOMBA TIT TQ 450 EFLUENTES": "BOMB-TQ 450 EFLUENTES",
  "HIDROPOLIS|TANQUE 450 EFLUENTES|BOMBA AUX TQ 450 EFLUENTES": "BOMB-TQ 450 EFLUENTES",
  "HIDROPOLIS|TANQUE 450 EFLUENTES|AGITADOR TQ 450 EFLUENTES": "AGIT-TQ 450 EFLUENTES",
  "HIDROPOLIS|TANQUE 450 PASTA|": "AGIT-TQ 450 PASTA",
  "HIDROPOLIS|TANQUE 450 PASTA|BOMBA TQ 450 PASTA": "BOMB-TQ 450 PASTA",
  "HIDROPOLIS|TANQUE 450 PASTA|AGITADOR TQ 450 PASTA": "AGIT-TQ 450 PASTA",
  "MESAS|SOTANO|BOMBA ALMIDON SPRAY 1": "QUI.BOALM1SP",
  "MESAS|SOTANO|BOMBA ALMIDON SPRAY 2": "QUI.BOALM2SP",
  "MESAS|SOTANO|BOMBA SEAL PIT CUP": "TAQC.BOSPITSE",
  "MESAS|SOTANO|BOMBA PILETA 102": "BOMB-PIL102C",
  "MESAS|SOTANO|BOMBA PILETA 270": "BOMB-PIL270I",
  "MESAS|SOTANO|BOMBA FAN DORSO": "MD.BOFAN",
  "MESAS|SOTANO|BOMBA FAN CUP": "DILC.BOTINDI",
  "MESAS|SOTANO|DEPURADOR V22 CUP": "MD.V22",
  "MESAS|SOTANO|BOMBA RECIRC DORSO": "MD.BOFAN",
  "MESAS|SOTANO|BOMBA RECUP DORSO": "MD.BOFAN",
  "MESAS|SOTANO|BOMBA CORTE POZO COUCH": "BOMCORTPC",
  "MESAS|SOTANO|DEPURADOR V22 DORSO": "MD.V22",
  "MESAS|SOTANO|BOMBA REFILE POZO COUCH": "BOMREFPC",
  "MESAS|SOTANO|AGITADOR POZO COUCH": "AGITPCOUCH",
  "MESAS|CUPERTINA|": "TRAQUEOCUP",
  "MESAS|CUPERTINA|CAJA FORM MESA CUP": "CAF-CUP",
  "MESAS|DORSO|": "TRAQUEODOR",
  "MESAS|DORSO|CAJA FORM MESA DORSO": "CAF-DOR",
  "MESAS|DORSO|CAJAS VACIO MESA DORSO": "MANDOS MESA DORSO",
  "MESAS|DORSO|ROLLOS MESA DORSO": "MANDOS MESA DORSO",
  "MESAS|DORSO|GUIA TELA MESA DORSO": "MANDOS MESA DORSO",
  "MESAS|DORSO|TELA MESA DORSO": "MANDOS MESA DORSO",
  "MESAS|DORSO|CUCHILLAS MESA DORSO": "MANDOS MESA DORSO",
  "MESAS|DORSO|REGADERAS MESA DORSO": "MANDOS MESA DORSO",
  "MESAS|CAPA INTERMEDIA|": "MANDOS MESA CAPA INTERMEDIA",
  "MESAS|CAPA INTERMEDIA|CAJA FORM MESA CI": "CAF-CI",
  "MESAS|TOP FORMER|": "TF.VENVACMFCS",
  "MESAS|TOP FORMER|ROLLOS TOP FORMER": "TF.VENVACMFCS",
  "MESAS|TOP FORMER|GUIA TELA TOP FORMER": "MC.M9MAN",
  "MESAS|TOP FORMER|TELA TOP FORMER": "MC.M9MAN",
  "MESAS|TOP FORMER|CUCHILLAS TOP FORMER": "TF.VENVACMFCS",
  "MESAS|TOP FORMER|REGADERAS TOP FORMER": "TF.VENVACMFCS",
  "MESAS|MANDOS MESAS|MANDO M7 ROLLO TRANSF CI": "MC.M7MAN",
  "MESAS|MANDOS MESAS|MANDO M4 RMT DORSO": "MC.M4MAN",
  "MESAS|MANDOS MESAS|MANDO M8 ROLLO AUX. CI": "MC.M8MAN",
  "MESAS|MANDOS MESAS|MANDO M5 ROLLO TRANSF DORSO": "MC.M5MAN",
  "MESAS|MANDOS MESAS|MANDO M1 RMT CUP": "MC.M1MAN",
  "MESAS|MANDOS MESAS|MANDO M2 ROLLO ASPIRANTE CUP": "MC.M1MAN",
  "MESAS|MANDOS MESAS|MANDO M9 TOP FORMER": "MC.M9MAN",
  "MESAS|MANDOS MESAS|MANDO M6 RMT CI": "MC.M6MAN",
  "MESAS|LOSA COMPRESORES MESAS|COMPRESOR CAJA MESA CI": "MI.CECO",
  "MESAS|LOSA COMPRESORES MESAS|VENTILADORES TOP FORMER": "TF.VENVACMFCS",
  "MESAS|LOSA COMPRESORES MESAS|COMPRESOR CAJA MESA CUP": "CAF-CUP",
  "MESAS|LOSA COMPRESORES MESAS|COMPRESOR CAJA MESA DORSO": "MD.CECO",
  "PRENSAS|PRIMER PRENSA|ROLLOS 1º PRENSA": "PR.LAMBO",
  "PRENSAS|PRIMER PRENSA|FIELTRO 1º PRENSA": "PR.LAMBO",
  "PRENSAS|PRIMER PRENSA|REGADERAS 1º PRENSA": "PR.LAMBO",
  "PRENSAS|PRIMER PRENSA|CUCHILLAS 1º PRENSA": "PR.LAMBO",
  "PRENSAS|SEGUNDA PRENSA|ROLLOS 2º PRENSA": "2P.M11MAN",
  "PRENSAS|SEGUNDA PRENSA|FIELTRO 2º PRENSA": "2P.M11MAN",
  "PRENSAS|SEGUNDA PRENSA|REGADERAS 2º PRENSA": "2P.M11MAN",
  "PRENSAS|SEGUNDA PRENSA|CUCHILLAS 2º PRENSA": "2P.M11MAN",
  "PRENSAS|TEM SEC|CENTRAL HIDRAULICA TEM SEC": "BO1TEMSEC",
  "PRENSAS|MANDOS PRENSAS|MANDO M10 1º PRENSA": "1P.M10MAN",
  "PRENSAS|MANDOS PRENSAS|MANDO M11 2º PRENSA": "2P.M11MAN",
  "PRENSAS|MANDOS PRENSAS|MANDO M12B TEMSEC 1º NIP": "TSNIP1.M12B",
  "PRENSAS|MANDOS PRENSAS|MANDO M12A TEMSEC CIL BASE": "TEMS.M12CIBA",
  "PRENSAS|MANDOS PRENSAS|MANDO M12C TEMSEC 2º NIP": "TSNIP2.M12C",
  "SECADORES|PRIMER BATERIA (1 AL 12)|TELA 1º BATERIA SUP": "MAN.M1S1",
  "SECADORES|PRIMER BATERIA (1 AL 12)|TELA 1º BATERIA INF": "MAN.M1I1",
  "SECADORES|SEGUNDA BATERIA (13 AL 24)|TELA 2º BATERIA SUP": "MAN.M2S1",
  "SECADORES|SEGUNDA BATERIA (13 AL 24)|TELA 2º BATERIA INF": "MAN.M2I1",
  "SECADORES|TERCER BATERIA (25 AL 35)|TELA 3º BATERIA SUP": "MAN.M3S1",
  "SECADORES|TERCER BATERIA (25 AL 35)|TELA 3º BATERIA INF": "MAN.M3I1",
  "SECADORES|MONOLUCIDO|MANDO MONOLUCIDO": "MONO.MAUX",
  "SECADORES|CUARTA BATERIA (36 AL 43)|TELA 4º BATERIA SUP": "INT.AC4Y5",
  "SECADORES|QUINTA BATERIA (44 AL 53)|TELA 5º BATERIA SUP": "INT.AC4Y5",
  "BOMBAS DE VACIO|BOMBAS DE VACIO|": "SUMID BBAS VACIO",
  "BOMBAS DE VACIO|BOMBAS DE VACIO|BOMBA VACIO 01": "VCIO.BO01",
  "BOMBAS DE VACIO|BOMBAS DE VACIO|BOMBA VACIO 02": "VCIO.BO01",
  "BOMBAS DE VACIO|BOMBAS DE VACIO|BOMBA VACIO 03": "VCIO.BO01",
  "BOMBAS DE VACIO|BOMBAS DE VACIO|BOMBA VACIO 04": "VCIO.BO01",
  "BOMBAS DE VACIO|BOMBAS DE VACIO|BOMBA VACIO 05": "VCIO.BO01",
  "BOMBAS DE VACIO|BOMBAS DE VACIO|BOMBA VACIO 06": "VCIO.BO01",
  "BOMBAS DE VACIO|BOMBAS DE VACIO|BOMBA VACIO 07": "VCIO.BO01",
  "BOMBAS DE VACIO|BOMBAS DE VACIO|BOMBA VACIO 08": "VCIO.BO01",
  "BOMBAS DE VACIO|BOMBAS DE VACIO|BOMBA VACIO 09": "VCIO.BO01",
  "BOMBAS DE VACIO|BOMBAS DE VACIO|BOMBA VACIO 10": "VCIO.BO01",
  "BOMBAS DE VACIO|BOMBAS DE VACIO|BOMBA VACIO 11": "VCIO.BO01",
  "BOMBAS DE VACIO|BOMBAS DE VACIO|BOMBA VACIO 12": "VCIO.BO01",
  "BOMBAS DE VACIO|BOMBAS DE VACIO|BOMBA VACIO 13": "VCIO.BO01",
  "BOMBAS DE VACIO|BOMBAS DE VACIO|BOMBA SELLO VACIO": "VCIO.BOAS",
  "BOMBAS DE VACIO|BOMBAS DE VACIO|BOMBA ELUTRIACION": "AGRE.BOELU",
  "BOMBAS DE VACIO|BOMBAS DE VACIO|BOMBA SUMIDERO": "VCIO.BOSUMI",
  "PLANTA CONDENSADO|BOMBA BC3 TQ VACIO|": "BC3TQVACIO",
  "PLANTA CONDENSADO|BOMBA BC5 TQ PULMON|": "BOMBC5TQPULMON",
  "PLANTA CONDENSADO|BOMBA BC6 TQ PULMON|": "BOMBC6TQPULMON",
  "VENTILADORES Y EXTRACTORES|LOSA TALLER MECANICO|VENT EXTRACTOR MONOLUCIDO": "MONO.VEEX",
  "VENTILADORES Y EXTRACTORES|LOSA TALLER MECANICO|VENT AIRE CAL INF PRESECADO": "INT.ACINFPRE",
  "CINTAS BAJO MAQ|CINTA BAJO MAQ 1|": "CICO.CINTABM1",
  "CINTAS BAJO MAQ|CINTA BAJO MAQ 2|": "CICO.CINTABM2",
  "CINTAS BAJO MAQ|CINTA BAJO MAQ 3|": "CICO.CINTABM3",
  "CINTAS BAJO MAQ|CINTA BAJO MAQ 4|": "CICO.CINTABM4",
  "CINTAS BAJO MAQ|CINTA BAJO MAQ 5|": "CICO.CINTABM5",
  "CINTAS BAJO MAQ|CINTA BAJO MAQ 6|": "CICO.CINTABM6",
  "CINTAS BAJO MAQ|CINTA BAJO MAQ 7|": "CICO.CINTABM7",
  "CINTAS BAJO MAQ|CINTA BAJO MAQ 8|": "CICO.CINTABM8",
  "CINTAS BAJO MAQ|CINTA BAJO MAQ 9|": "CICO.CINTABM9",
  "PULPER BAJO MAQUINA|PULPER BAJO MAQUINA|": "BOMBEO PBM",
  "ESTUCADO|UNI BAR|": "CONTRARODILLOUB",
  "ESTUCADO|UNI BAR|ESTUCADORA UNI BAR": "CONTRARODILLOUB",
  "ESTUCADO|UNI BAR|SOLARONIC UNI BAR": "CONTRARODILLOUB",
  "ESTUCADO|UNI BAR|VENT AIRE COMB MAXON 2 UNI BAR": "MAXO.IIVECO",
  "ESTUCADO|UNI BAR|VENT AIRE RECIRC MAXON 2 UNI BAR": "MAXO.IIVECO",
  "ESTUCADO|UNI BAR|VENT AIRE COMB SOLARONIC UNI BAR": "SOL4.VERE",
  "ESTUCADO|UNI BAR|VENT RECIRC SOLARONIC UNI BAR": "SOL4.VERE",
  "ESTUCADO|UNI BAR|CORREAS MANDO ROLLOS UNI BAR": "MANRA-UB",
  "ESTUCADO|UNI BAR|CONTRARODILLO UNI BAR": "CONTRARODILLOUB",
  "ESTUCADO|UNI BAR|ROLLO APLICADOR UNI BAR": "RA-UB",
  "ESTUCADO|UNI BAR|ROLLOS PAPEL UNI BAR": "CONTRARODILLOUB",
  "ESTUCADO|UNI BAR|MANDO M17 CONTRARODILLO UNI BAR": "MANRA-UB",
  "ESTUCADO|UNI BAR|MANDO ROLLO APLICADOR UNI BAR": "MANRA-UB",
  "ESTUCADO|UNI BAR|SOGA UNI BAR": "CONTRARODILLOUB",
  "ESTUCADO|UNI BAR|VARILLA UNI BAR": "VUB",
  "ESTUCADO|CALANDRA 1|": "CAL1.MANS",
  "ESTUCADO|CALANDRA 1|CALANDRA 1": "CAL1.MANS",
  "ESTUCADO|CALANDRA 1|CENTRAL HIDRAULICA CALANDRA 1": "CAL1.CHIDRA",
  "ESTUCADO|CALANDRA 1|MANDO M14 CALANDRA 1": "CAL1.MANS",
  "ESTUCADO|CALANDRA 1|ROLLO SUP KUSTER CALANDRA 1": "CAL1.CHIDRA",
  "ESTUCADO|CALANDRA 1|ROLLO INF CALANDRA 1": "CAL1.CHIDRA",
  "ESTUCADO|VARI BAR|": "CONTRARODILLOVB",
  "ESTUCADO|VARI BAR|ESTUCADORA VARI BAR": "CONTRARODILLOVB",
  "ESTUCADO|VARI BAR|VAPOR ESTUFAS VARI BAR": "CONTRARODILLOVB",
  "ESTUCADO|VARI BAR|VENT NA01 VARI BAR": "VABA.INTNB01",
  "ESTUCADO|VARI BAR|INTERCAMBIADOR NA01 VARI BAR": "VABA.INTNB01",
  "ESTUCADO|VARI BAR|MANDO M16 SOGA VARI BAR": "VABA.SO",
  "ESTUCADO|VARI BAR|VARILLA VARI BAR": "VVB",
  "ESTUCADO|VARI BAR|CORREAS MANDO ROLLOS VARI BAR": "MANCONTRARODILLOVB",
  "ESTUCADO|VARI BAR|CONTRARODILLO VARI BAR": "CONTRARODILLOVB",
  "ESTUCADO|VARI BAR|ROLLO APLICADOR VARI BAR": "MANRA-VB",
  "ESTUCADO|VARI BAR|ROLLOS PAPEL VARI BAR": "CONTRARODILLOVB",
  "ESTUCADO|VARI BAR|MANDO M15 SOGAS VARI BAR": "VB.M15",
  "ESTUCADO|VARI BAR|MANDO M16 CONTRARODILLO VARI BAR": "MANCONTRARODILLOVB",
  "ESTUCADO|VARI BAR|MANDO ROLLO APLICADOR VARI BAR": "MANRA-VB",
  "ESTUCADO|VARI BAR|SOGA VARI BAR": "VABA.SO",
  "ESTUCADO|VARI BAR|TENSOR NEUM SOGA EXT VARI BAR": "VABA.SO",
  "ESTUCADO|VARI BAR|TENSOR NEUM SOGA INT VARI BAR": "VABA.SO",
  "ESTUCADO|LABIO SOPLADOR|": "CONTRARODILLOLS",
  "ESTUCADO|LABIO SOPLADOR|ESTUCADORA LABIO SOPLADOR": "CONTRARODILLOLS",
  "ESTUCADO|LABIO SOPLADOR|VAPOR ESTUFAS LABIO SOPLADOR": "CONTRARODILLOLS",
  "ESTUCADO|LABIO SOPLADOR|SOLARONIC LABIO SOPLADOR": "CONTRARODILLOLS",
  "ESTUCADO|LABIO SOPLADOR|CONTRARODILLO LABIO SOPLADOR": "CONTRARODILLOLS",
  "ESTUCADO|LABIO SOPLADOR|ROLLO APLICADOR LABIO SOPLADOR": "RA-LS",
  "ESTUCADO|LABIO SOPLADOR|ROLLO PREALISADOS LABIO SOPLADOR": "RA-LS",
  "ESTUCADO|LABIO SOPLADOR|ROLLO SELLADOR CAJA LABIO SOPLADOR": "RA-LS",
  "ESTUCADO|LABIO SOPLADOR|ROLLOS PAPEL LABIO SOPLADOR": "CONTRARODILLOLS",
  "ESTUCADO|LABIO SOPLADOR|MANDO M19 SOGA LABIO SOPLADOR": "LABS.SO",
  "ESTUCADO|LABIO SOPLADOR|CORREAS MANDO ROLLOS LABIO SOPLADOR": "MANRA-LS",
  "ESTUCADO|LABIO SOPLADOR|SOGA 1 LABIO SOPLADOR": "LABS.SO",
  "ESTUCADO|LABIO SOPLADOR|TENSOR NEUM SOGA 1 LABIO SOPLADOR": "LABS.SO",
  "ESTUCADO|LABIO SOPLADOR|SOGA 3 LABIO SOPLADOR": "LABS.SO",
  "ESTUCADO|LABIO SOPLADOR|TENSOR NEUM SOGA 3 LABIO SOPLADOR": "LABS.SO",
  "ESTUCADO|LABIO SOPLADOR|VENT AIRE COMB SOLARONIC LABIO SOPLADOR": "SOL3.VECO",
  "ESTUCADO|LABIO SOPLADOR|VENT RECIRC SOLARONIC LABIO SOPLADOR": "SOL3.VECO",
  "ESTUCADO|LABIO SOPLADOR|SOPLADOR LABIO SOPLADOR": "CONTRARODILLOLS",
  "ESTUCADO|LABIO SOPLADOR|VENT EXTRACTOR POLVILLO LABIO SOPLADOR": "LABS.VEEXPOL",
  "ESTUCADO|COMBI BLADE|": "CONTRARODILLOCB",
  "ESTUCADO|COMBI BLADE|ESTUCADORA COMBI BLADE": "CONTRARODILLOCB",
  "ESTUCADO|COMBI BLADE|SOLARONIC COMBI BLADE": "CONTRARODILLOCB",
  "ESTUCADO|COMBI BLADE|CORREAS MANDO ROLLOS COMBI BLADE": "MANCONTRARODILLOCB",
  "ESTUCADO|COMBI BLADE|CONTRARODILLO COMBI BLADE": "CONTRARODILLOCB",
  "ESTUCADO|COMBI BLADE|MANDO M21 SOGAS COMBI BLADE": "MANCONTRARODILLOCB",
  "ESTUCADO|COMBI BLADE|MANDO ROLLO APLICADOR COMBI BLADE": "MANRA-CB",
  "ESTUCADO|COMBI BLADE|MANDO CONTRARODILLO COMBI BLADE": "MANCONTRARODILLOCB",
  "ESTUCADO|COMBI BLADE|ROLLO APLICADOR COMBI BLADE": "RA-CB",
  "ESTUCADO|COMBI BLADE|ROLLOS PAPEL COMBI BLADE": "CONTRARODILLOCB",
  "ESTUCADO|COMBI BLADE|TENSOR NEUM SOGA EXT COMBI BLADE": "COMB.SO",
  "ESTUCADO|COMBI BLADE|TENSOR NEUM SOGA INT COMBI BLADE": "COMB.SO",
  "ESTUCADO|COMBI BLADE|VARILLA COMBI BLADE": "VCB",
  "ESTUCADO|COMBI BLADE|VENT AIRE COMB MAXON 1 COMBI BLADE": "MAXO.VECO",
  "ESTUCADO|COMBI BLADE|VENT AIRE RECIRC MAXON 1 COMBI BLADE": "MAXO.VECO",
  "ESTUCADO|COMBI BLADE|VENT AIRE COMB SOLARONIC COMBI BLADE": "SOL2.VECO",
  "ESTUCADO|COMBI BLADE|VENT AIRE RECIRC SOLARONIC COMBI BLADE": "SOL2.VECO",
  "ESTUCADO|SOTANO ESTUCADO|ESTACION FINAL UNI BAR": "ESTF.AGF4UNIB",
  "ESTUCADO|SOTANO ESTUCADO|AGITADOR ESTACION FINAL F3 UNI BAR": "ESTF.AGF4UNIB",
  "ESTUCADO|SOTANO ESTUCADO|ZARANDA ESTACION FINAL F3 UNI BAR": "ESTF.ZAF4UNIB",
  "ESTUCADO|SOTANO ESTUCADO|BOMBA PF3 ESTACION FINAL UNI BAR": "UB.BOPF3",
  "ESTUCADO|SOTANO ESTUCADO|ESTACION FINAL VARI BAR": "ESTF.AGF1VARI",
  "ESTUCADO|SOTANO ESTUCADO|AGITADOR ESTACION FINAL F1 VARI BAR": "ESTF.AGF1VARI",
  "ESTUCADO|SOTANO ESTUCADO|ZARANDA ESTACION FINAL F1 VARI BAR": "ESTF.ZAF1VARI",
  "ESTUCADO|SOTANO ESTUCADO|BOMBA PF1 ESTACION FINAL VARI BAR": "VB.BOPF1",
  "ESTUCADO|SOTANO ESTUCADO|ESTACION FINAL LABIO SOPLADOR": "ESTF.AGF2LABI",
  "ESTUCADO|SOTANO ESTUCADO|AGITADOR ESTACION FINAL F2 LABIO SOPLADOR": "ESTF.AGF2LABI",
  "ESTUCADO|SOTANO ESTUCADO|ZARANDA ESTACION FINAL F2 LABIO SOPLADOR": "ESTF.ZAF2LABI",
  "ESTUCADO|SOTANO ESTUCADO|BOMBA PF2 ESTACION FINAL LABIO SOPLADOR": "LS.BOPF2",
  "ESTUCADO|SOTANO ESTUCADO|ESTACION FINAL COMBI BLADE": "ESTF.AGF4COMB",
  "ESTUCADO|SOTANO ESTUCADO|AGITADOR ESTACION FINAL PF4 COMBI BLADE": "ESTF.AGF4COMB",
  "ESTUCADO|SOTANO ESTUCADO|ZARANDA ESTACION FINAL F4 COMBI BLADE": "ESTF.ZARCOMB",
  "ESTUCADO|SOTANO ESTUCADO|BOMBA PF4 ESTACION FINAL COMBI BLADE": "CB.BOPF4",
  "ESTUCADO|SOTANO ESTUCADO|BOMBA RECUPERO SALSA ESTACION FINAL COMBI BLADE": "CB.BOPF4",
  "ESTUCADO|SOTANO ESTUCADO|FILTROS RONNINGER PETER COMBI BLADE": "ESTF.FI1RONCB",
  "SEXTA BATERIA|ENFRIADORES|BOMBA RECUPERO AGUA ENFRIADORES": "BOMB-TREA.I",
  "SEXTA BATERIA|CALANDRA 2|": "CUINFCAL2",
  "SEXTA BATERIA|CALANDRA 2|CALANDRA 2": "CUINFCAL2",
  "SEXTA BATERIA|CALANDRA 2|CUCHILLAS CALANDRA 2": "CUINFCAL2",
  "SEXTA BATERIA|CALANDRA 2|MANDO CALANDRA 2": "CAL2.MAN",
  "POPE|POPE|PUENTE GRUA 10T POPE": "GRUA.ELEVCPPO",
  "POPE|POPE|BARRAS BOBINAS POPE": "ACPOPE.MAN",
  "POPE|POPE|MANDO POPE": "POPE.MAN",
  "POPE|POPE|ACELERADOR DE BARRA POPE": "ACPOPE.MAN",
  "POPE|POPE|ESCANER VALMET": "ESCANER VM",
  "CELLIER|CELLIER|": "GRUA.MTACARCE",
  "CELLIER|CELLIER|AGITADOR TQ B1": "AGIT-CELL.TQB1",
  "CELLIER|CELLIER|AGITADOR TQ COCINADOR C1": "AGCOC1",
  "CELLIER|CELLIER|AGITADOR TQ COCINADOR C2": "AGCOC2",
  "CELLIER|CELLIER|BOMBA B1 AGUA SELLO DILUTORES": "CELL.BOAGSED1",
  "CELLIER|CELLIER|BOMBA B2 AGUA SELLO DILUTORES": "CELL.BOAGSED1",
  "CELLIER|CELLIER|BOMBA TQ E1 Y E2": "CELL.BOPE1",
  "CELLIER|CELLIER|BOMBA TQ E4 Y E5": "CELL.BOPE2",
  "CELLIER|CELLIER|BOMBA TQ E6": "CELL.BOPE3",
  "CELLIER|CELLIER|BOMBA TQ E7": "CELL.BOPE4",
  "CELLIER|CELLIER|DILUTOR 1": "CELL.DL01",
  "CELLIER|CELLIER|DILUTOR 2": "CELL.DL02",
  "CELLIER|CELLIER|DILUTOR 3": "CELL.DL03",
  "CELLIER|CELLIER|SOPLADOR TRANSPORTE CAOLIN": "CELL.SOPCA",
  "CELLIER|CELLIER|VENT EXTRACTOR DILUTORES 2 Y 3": "CELL.VEXPD2Y3",
  "ALISTAMIENTO|REBOBINADORA|VENT EXTRACTOR POLVILLO AXIAL REBOBINADORA": "REB-VEAXEXPO",
  "ALISTAMIENTO|REBOBINADORA|VENT EXTRACTOR POLVILLO CENTRIFUGO REBOBINADORA": "REB-VECEEXPO",
  "ALISTAMIENTO|PULPER REFILE REBOBINADORA|": "PULPER REFILE",
  "ALISTAMIENTO|PULPER REFILE REBOBINADORA|BOMBA PULPER REFILE": "BOMPULPER REFILE",
  "ALISTAMIENTO|PULPER REFILE REBOBINADORA|MANDO PULPER REFILE": "PULPER REFILE",
  "ALISTAMIENTO|PULPER REFILE REBOBINADORA|PULPER REFILE": "PULPER REFILE",
  "ALISTAMIENTO|VOLCADOR DE BOBINAS|": "ALI.VBOB",
  "ALISTAMIENTO|VOLCADOR DE BOBINAS|CILINDORS HIDRAULICOS VOLCADOR DE BOBINAS": "ALI.VBOB",
  "ALISTAMIENTO|VOLCADOR DE BOBINAS|CENTRAL HIDRAULICA VOLCADOR DE BOBINAS": "ALI.VBOB",
  "ALISTAMIENTO|VOLCADOR DE BOBINAS|CAJAS RODAMIENTO VOLCADOR DE BOBINAS": "ALI.VBOB",
  "ALISTAMIENTO|ZONA CORTADORA|": "LUG.ALIS.CORTADORA",
  "ALISTAMIENTO|DEPOSITO|": "LUG.ALIS.DEPOSITO",
  "LABORATORIO|LABORATORIO DE CALIDAD|": "LUG.LAB.CALIDAD",
  "LABORATORIO|EQUIPOS DE ENSAYO|": "LUG.LAB.ENSAYOS",
  "PULPER BAJO MAQUINA|BOMBA PBM|": "BOMBEO PBM",
  "PRENSAS|PRIMER PRENSA|FUELLES NEU 1º PRENSA": "LUG.PREN.PRENSA1",
  "PRENSAS|PRIMER PRENSA|GUIAS FIELTRO 1º PRENSA": "LUG.PREN.PRENSA1",
  "POPE|POPE|CILINDRO ENROLLADORA POPE": "POPE.MAN",
  "POPE|POPE|CILINDROS NEUMATICOS POPE": "LUG.POPE",
  "PLANTA DE PASTA|CONTROLADORES|": "LUG.PP.GENERAL",
  "SECADORES|PRIMER BATERIA (1 AL 12)|SECADORES 1º BAT (1 AL 12)": "LUG.SEC.BAT1",
  "SECADORES|SEGUNDA BATERIA (13 AL 24)|SECADORES 2º BAT (13 AL 24)": "LUG.SEC.BAT2",
  "SECADORES|TERCER BATERIA (25 AL 35)|SECADORES 3º BAT (25 AL 35)": "LUG.SEC.BAT3",
  "SECADORES|TERCER BATERIA (25 AL 35)|VAPOR SEC 3º BAT": "LUG.SEC.BAT3",
  "SECADORES|CUARTA BATERIA (36 AL 43)|MANDOS 4º BAT": "LUG.SEC.BAT4",
  "SECADORES|QUINTA BATERIA (44 AL 53)|POLEAS DE SOGA 5º BAT": "LUG.SEC.BAT5",
  "SECADORES|QUINTA BATERIA (44 AL 53)|SECADORES 5º BAT (44 AL 53)": "LUG.SEC.BAT5",
  "SECADORES|SEGUNDA BATERIA (13 AL 24)|CUCHILLAS 2º BAT": "CUCH.SEC",
  "SECADORES|MONOLUCIDO|GUIA FIELTRO MONOLUCIDO": "LUG.SEC.MONO",
  "HIDROPOLIS|CANAL EFLUENTES|RASTRILLO": "EFLU.RASTRI",
  "HIDROPOLIS|PLANTA ALTA|KROFTA": "EFLUSEDI",
  "SERVICIOS AUXILIARES|PTA FUEL OIL|": "LUG.SSAA.FUELOIL",
  "SERVICIOS AUXILIARES|CALDERA 4|VTF CALDERA 4": "LUG.SSAA.CALDERA4",
  "SERVICIOS AUXILIARES|CALDERA 4|VAPOR CALDERA 4": "LUG.SSAA.CALDERA4",
  "SERVICIOS AUXILIARES|PTA GAS|": "LUG.SSAA.GAS",
  "ALISTAMIENTO|REBOBINADORA|REBOBINADORA": "LUG.ALIS.REBOB",
  "ALISTAMIENTO|REBOBINADORA|ACOPLE BOBINA MADRE": "LUG.ALIS.REBOB",
  "PLANTA DE PASTA|SECTOR REFINOS Y FIBERIZER|FIBERIZER 101": "FIBC.F1",
  "PLANTA DE PASTA|SECTOR REFINOS Y FIBERIZER|FIBERIZER 301": "FISEP 301",
  "PLANTA DE PASTA|SECTOR REFINOS Y FIBERIZER|REFINADOR 302": "REF.R302",
  "PLANTA DE PASTA|SECTOR REFINOS Y FIBERIZER|REFINADOR 101": "REF.R101",
  "PRENSAS|TEM SEC|FIELTRO TEM SEC": "LUG.PREN.TEMSEC",
};

/* Árbol de 2 niveles para las pantallas: ÁREA -> { Descripción: [] } */
const ARBOL_EQUIPO = {};
const EQUIPO_POR_SISTEMA = {};
EQUIPOS.forEach(function (e) {
  (ARBOL_EQUIPO[e[2]] = ARBOL_EQUIPO[e[2]] || {})[e[1]] = [];
  EQUIPO_POR_SISTEMA[e[0]] = { sistema: e[0], descripcion: e[1], area: e[2] };
});
/* Sistema de un lugar elegido por área + descripción */
function sistemaDe(area, descripcion) {
  const e = EQUIPOS.find(function (x) { return x[2] === area && x[1] === descripcion; }) || EQUIPOS.find(function (x) { return x[1] === descripcion; });
  return e ? e[0] : '';
}
/* Ubicación del árbol anterior -> equipo nuevo (o null) */
function equipoDeUbicacionVieja(area, sub, eq) {
  const s = MAPEO_ARBOL_VIEJO[[area || '', sub || '', eq || ''].join('|')] || MAPEO_ARBOL_VIEJO[[area || '', sub || '', ''].join('|')];
  return s ? EQUIPO_POR_SISTEMA[s] : null;
}
